// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skissm/register_user_request_payload.proto

package org.e2eelab.skissm.proto;

public final class RegisterUserRequestPayload {
  private RegisterUserRequestPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface register_user_request_payloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skissm.register_user_request_payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string authenticator = 3;</code>
     * @return The authenticator.
     */
    java.lang.String getAuthenticator();
    /**
     * <code>string authenticator = 3;</code>
     * @return The bytes for authenticator.
     */
    com.google.protobuf.ByteString
        getAuthenticatorBytes();

    /**
     * <code>string auth_code = 4;</code>
     * @return The authCode.
     */
    java.lang.String getAuthCode();
    /**
     * <code>string auth_code = 4;</code>
     * @return The bytes for authCode.
     */
    com.google.protobuf.ByteString
        getAuthCodeBytes();

    /**
     * <code>bytes identity_key_public = 5;</code>
     * @return The identityKeyPublic.
     */
    com.google.protobuf.ByteString getIdentityKeyPublic();

    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     * @return Whether the signedPreKeyPublic field is set.
     */
    boolean hasSignedPreKeyPublic();
    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     * @return The signedPreKeyPublic.
     */
    org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public getSignedPreKeyPublic();
    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     */
    org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder getSignedPreKeyPublicOrBuilder();

    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> 
        getOneTimePreKeysList();
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public getOneTimePreKeys(int index);
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    int getOneTimePreKeysCount();
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    java.util.List<? extends org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder> 
        getOneTimePreKeysOrBuilderList();
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder getOneTimePreKeysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code skissm.register_user_request_payload}
   */
  public static final class register_user_request_payload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:skissm.register_user_request_payload)
      register_user_request_payloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use register_user_request_payload.newBuilder() to construct.
    private register_user_request_payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private register_user_request_payload() {
      userName_ = "";
      deviceId_ = "";
      authenticator_ = "";
      authCode_ = "";
      identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      oneTimePreKeys_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new register_user_request_payload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private register_user_request_payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              authenticator_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              authCode_ = s;
              break;
            }
            case 42: {

              identityKeyPublic_ = input.readBytes();
              break;
            }
            case 50: {
              org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder subBuilder = null;
              if (signedPreKeyPublic_ != null) {
                subBuilder = signedPreKeyPublic_.toBuilder();
              }
              signedPreKeyPublic_ = input.readMessage(org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(signedPreKeyPublic_);
                signedPreKeyPublic_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                oneTimePreKeys_ = new java.util.ArrayList<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public>();
                mutable_bitField0_ |= 0x00000001;
              }
              oneTimePreKeys_.add(
                  input.readMessage(org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          oneTimePreKeys_ = java.util.Collections.unmodifiableList(oneTimePreKeys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.e2eelab.skissm.proto.RegisterUserRequestPayload.internal_static_skissm_register_user_request_payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.e2eelab.skissm.proto.RegisterUserRequestPayload.internal_static_skissm_register_user_request_payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.class, org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.Builder.class);
    }

    public static final int USER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>string user_name = 1;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 1;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHENTICATOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object authenticator_;
    /**
     * <code>string authenticator = 3;</code>
     * @return The authenticator.
     */
    @java.lang.Override
    public java.lang.String getAuthenticator() {
      java.lang.Object ref = authenticator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authenticator_ = s;
        return s;
      }
    }
    /**
     * <code>string authenticator = 3;</code>
     * @return The bytes for authenticator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthenticatorBytes() {
      java.lang.Object ref = authenticator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authenticator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object authCode_;
    /**
     * <code>string auth_code = 4;</code>
     * @return The authCode.
     */
    @java.lang.Override
    public java.lang.String getAuthCode() {
      java.lang.Object ref = authCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authCode_ = s;
        return s;
      }
    }
    /**
     * <code>string auth_code = 4;</code>
     * @return The bytes for authCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthCodeBytes() {
      java.lang.Object ref = authCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITY_KEY_PUBLIC_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString identityKeyPublic_;
    /**
     * <code>bytes identity_key_public = 5;</code>
     * @return The identityKeyPublic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIdentityKeyPublic() {
      return identityKeyPublic_;
    }

    public static final int SIGNED_PRE_KEY_PUBLIC_FIELD_NUMBER = 6;
    private org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public signedPreKeyPublic_;
    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     * @return Whether the signedPreKeyPublic field is set.
     */
    @java.lang.Override
    public boolean hasSignedPreKeyPublic() {
      return signedPreKeyPublic_ != null;
    }
    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     * @return The signedPreKeyPublic.
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public getSignedPreKeyPublic() {
      return signedPreKeyPublic_ == null ? org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.getDefaultInstance() : signedPreKeyPublic_;
    }
    /**
     * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder getSignedPreKeyPublicOrBuilder() {
      return getSignedPreKeyPublic();
    }

    public static final int ONE_TIME_PRE_KEYS_FIELD_NUMBER = 7;
    private java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> oneTimePreKeys_;
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    @java.lang.Override
    public java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> getOneTimePreKeysList() {
      return oneTimePreKeys_;
    }
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder> 
        getOneTimePreKeysOrBuilderList() {
      return oneTimePreKeys_;
    }
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    @java.lang.Override
    public int getOneTimePreKeysCount() {
      return oneTimePreKeys_.size();
    }
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public getOneTimePreKeys(int index) {
      return oneTimePreKeys_.get(index);
    }
    /**
     * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder getOneTimePreKeysOrBuilder(
        int index) {
      return oneTimePreKeys_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authenticator_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, authenticator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authCode_);
      }
      if (!identityKeyPublic_.isEmpty()) {
        output.writeBytes(5, identityKeyPublic_);
      }
      if (signedPreKeyPublic_ != null) {
        output.writeMessage(6, getSignedPreKeyPublic());
      }
      for (int i = 0; i < oneTimePreKeys_.size(); i++) {
        output.writeMessage(7, oneTimePreKeys_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authenticator_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, authenticator_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authCode_);
      }
      if (!identityKeyPublic_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, identityKeyPublic_);
      }
      if (signedPreKeyPublic_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getSignedPreKeyPublic());
      }
      for (int i = 0; i < oneTimePreKeys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, oneTimePreKeys_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload)) {
        return super.equals(obj);
      }
      org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload other = (org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload) obj;

      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (!getAuthenticator()
          .equals(other.getAuthenticator())) return false;
      if (!getAuthCode()
          .equals(other.getAuthCode())) return false;
      if (!getIdentityKeyPublic()
          .equals(other.getIdentityKeyPublic())) return false;
      if (hasSignedPreKeyPublic() != other.hasSignedPreKeyPublic()) return false;
      if (hasSignedPreKeyPublic()) {
        if (!getSignedPreKeyPublic()
            .equals(other.getSignedPreKeyPublic())) return false;
      }
      if (!getOneTimePreKeysList()
          .equals(other.getOneTimePreKeysList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + AUTHENTICATOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthenticator().hashCode();
      hash = (37 * hash) + AUTH_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAuthCode().hashCode();
      hash = (37 * hash) + IDENTITY_KEY_PUBLIC_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityKeyPublic().hashCode();
      if (hasSignedPreKeyPublic()) {
        hash = (37 * hash) + SIGNED_PRE_KEY_PUBLIC_FIELD_NUMBER;
        hash = (53 * hash) + getSignedPreKeyPublic().hashCode();
      }
      if (getOneTimePreKeysCount() > 0) {
        hash = (37 * hash) + ONE_TIME_PRE_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getOneTimePreKeysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code skissm.register_user_request_payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:skissm.register_user_request_payload)
        org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.e2eelab.skissm.proto.RegisterUserRequestPayload.internal_static_skissm_register_user_request_payload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.e2eelab.skissm.proto.RegisterUserRequestPayload.internal_static_skissm_register_user_request_payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.class, org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.Builder.class);
      }

      // Construct using org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOneTimePreKeysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userName_ = "";

        deviceId_ = "";

        authenticator_ = "";

        authCode_ = "";

        identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;

        if (signedPreKeyPublicBuilder_ == null) {
          signedPreKeyPublic_ = null;
        } else {
          signedPreKeyPublic_ = null;
          signedPreKeyPublicBuilder_ = null;
        }
        if (oneTimePreKeysBuilder_ == null) {
          oneTimePreKeys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          oneTimePreKeysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.e2eelab.skissm.proto.RegisterUserRequestPayload.internal_static_skissm_register_user_request_payload_descriptor;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload getDefaultInstanceForType() {
        return org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.getDefaultInstance();
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload build() {
        org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload buildPartial() {
        org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload result = new org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload(this);
        int from_bitField0_ = bitField0_;
        result.userName_ = userName_;
        result.deviceId_ = deviceId_;
        result.authenticator_ = authenticator_;
        result.authCode_ = authCode_;
        result.identityKeyPublic_ = identityKeyPublic_;
        if (signedPreKeyPublicBuilder_ == null) {
          result.signedPreKeyPublic_ = signedPreKeyPublic_;
        } else {
          result.signedPreKeyPublic_ = signedPreKeyPublicBuilder_.build();
        }
        if (oneTimePreKeysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            oneTimePreKeys_ = java.util.Collections.unmodifiableList(oneTimePreKeys_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.oneTimePreKeys_ = oneTimePreKeys_;
        } else {
          result.oneTimePreKeys_ = oneTimePreKeysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload) {
          return mergeFrom((org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload other) {
        if (other == org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getAuthenticator().isEmpty()) {
          authenticator_ = other.authenticator_;
          onChanged();
        }
        if (!other.getAuthCode().isEmpty()) {
          authCode_ = other.authCode_;
          onChanged();
        }
        if (other.getIdentityKeyPublic() != com.google.protobuf.ByteString.EMPTY) {
          setIdentityKeyPublic(other.getIdentityKeyPublic());
        }
        if (other.hasSignedPreKeyPublic()) {
          mergeSignedPreKeyPublic(other.getSignedPreKeyPublic());
        }
        if (oneTimePreKeysBuilder_ == null) {
          if (!other.oneTimePreKeys_.isEmpty()) {
            if (oneTimePreKeys_.isEmpty()) {
              oneTimePreKeys_ = other.oneTimePreKeys_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOneTimePreKeysIsMutable();
              oneTimePreKeys_.addAll(other.oneTimePreKeys_);
            }
            onChanged();
          }
        } else {
          if (!other.oneTimePreKeys_.isEmpty()) {
            if (oneTimePreKeysBuilder_.isEmpty()) {
              oneTimePreKeysBuilder_.dispose();
              oneTimePreKeysBuilder_ = null;
              oneTimePreKeys_ = other.oneTimePreKeys_;
              bitField0_ = (bitField0_ & ~0x00000001);
              oneTimePreKeysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOneTimePreKeysFieldBuilder() : null;
            } else {
              oneTimePreKeysBuilder_.addAllMessages(other.oneTimePreKeys_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 1;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 1;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string device_id = 2;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_id = 2;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_id = 2;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 2;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authenticator_ = "";
      /**
       * <code>string authenticator = 3;</code>
       * @return The authenticator.
       */
      public java.lang.String getAuthenticator() {
        java.lang.Object ref = authenticator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authenticator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authenticator = 3;</code>
       * @return The bytes for authenticator.
       */
      public com.google.protobuf.ByteString
          getAuthenticatorBytes() {
        java.lang.Object ref = authenticator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authenticator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authenticator = 3;</code>
       * @param value The authenticator to set.
       * @return This builder for chaining.
       */
      public Builder setAuthenticator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authenticator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authenticator = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthenticator() {
        
        authenticator_ = getDefaultInstance().getAuthenticator();
        onChanged();
        return this;
      }
      /**
       * <code>string authenticator = 3;</code>
       * @param value The bytes for authenticator to set.
       * @return This builder for chaining.
       */
      public Builder setAuthenticatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authenticator_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authCode_ = "";
      /**
       * <code>string auth_code = 4;</code>
       * @return The authCode.
       */
      public java.lang.String getAuthCode() {
        java.lang.Object ref = authCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string auth_code = 4;</code>
       * @return The bytes for authCode.
       */
      public com.google.protobuf.ByteString
          getAuthCodeBytes() {
        java.lang.Object ref = authCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string auth_code = 4;</code>
       * @param value The authCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string auth_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthCode() {
        
        authCode_ = getDefaultInstance().getAuthCode();
        onChanged();
        return this;
      }
      /**
       * <code>string auth_code = 4;</code>
       * @param value The bytes for authCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authCode_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes identity_key_public = 5;</code>
       * @return The identityKeyPublic.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIdentityKeyPublic() {
        return identityKeyPublic_;
      }
      /**
       * <code>bytes identity_key_public = 5;</code>
       * @param value The identityKeyPublic to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityKeyPublic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityKeyPublic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes identity_key_public = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityKeyPublic() {
        
        identityKeyPublic_ = getDefaultInstance().getIdentityKeyPublic();
        onChanged();
        return this;
      }

      private org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public signedPreKeyPublic_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder> signedPreKeyPublicBuilder_;
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       * @return Whether the signedPreKeyPublic field is set.
       */
      public boolean hasSignedPreKeyPublic() {
        return signedPreKeyPublicBuilder_ != null || signedPreKeyPublic_ != null;
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       * @return The signedPreKeyPublic.
       */
      public org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public getSignedPreKeyPublic() {
        if (signedPreKeyPublicBuilder_ == null) {
          return signedPreKeyPublic_ == null ? org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.getDefaultInstance() : signedPreKeyPublic_;
        } else {
          return signedPreKeyPublicBuilder_.getMessage();
        }
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public Builder setSignedPreKeyPublic(org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public value) {
        if (signedPreKeyPublicBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          signedPreKeyPublic_ = value;
          onChanged();
        } else {
          signedPreKeyPublicBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public Builder setSignedPreKeyPublic(
          org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder builderForValue) {
        if (signedPreKeyPublicBuilder_ == null) {
          signedPreKeyPublic_ = builderForValue.build();
          onChanged();
        } else {
          signedPreKeyPublicBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public Builder mergeSignedPreKeyPublic(org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public value) {
        if (signedPreKeyPublicBuilder_ == null) {
          if (signedPreKeyPublic_ != null) {
            signedPreKeyPublic_ =
              org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.newBuilder(signedPreKeyPublic_).mergeFrom(value).buildPartial();
          } else {
            signedPreKeyPublic_ = value;
          }
          onChanged();
        } else {
          signedPreKeyPublicBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public Builder clearSignedPreKeyPublic() {
        if (signedPreKeyPublicBuilder_ == null) {
          signedPreKeyPublic_ = null;
          onChanged();
        } else {
          signedPreKeyPublic_ = null;
          signedPreKeyPublicBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder getSignedPreKeyPublicBuilder() {
        
        onChanged();
        return getSignedPreKeyPublicFieldBuilder().getBuilder();
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      public org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder getSignedPreKeyPublicOrBuilder() {
        if (signedPreKeyPublicBuilder_ != null) {
          return signedPreKeyPublicBuilder_.getMessageOrBuilder();
        } else {
          return signedPreKeyPublic_ == null ?
              org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.getDefaultInstance() : signedPreKeyPublic_;
        }
      }
      /**
       * <code>.skissm.signed_pre_key_public signed_pre_key_public = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder> 
          getSignedPreKeyPublicFieldBuilder() {
        if (signedPreKeyPublicBuilder_ == null) {
          signedPreKeyPublicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_public.Builder, org.e2eelab.skissm.proto.SignedPreKeyPublic.signed_pre_key_publicOrBuilder>(
                  getSignedPreKeyPublic(),
                  getParentForChildren(),
                  isClean());
          signedPreKeyPublic_ = null;
        }
        return signedPreKeyPublicBuilder_;
      }

      private java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> oneTimePreKeys_ =
        java.util.Collections.emptyList();
      private void ensureOneTimePreKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          oneTimePreKeys_ = new java.util.ArrayList<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public>(oneTimePreKeys_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder> oneTimePreKeysBuilder_;

      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> getOneTimePreKeysList() {
        if (oneTimePreKeysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(oneTimePreKeys_);
        } else {
          return oneTimePreKeysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public int getOneTimePreKeysCount() {
        if (oneTimePreKeysBuilder_ == null) {
          return oneTimePreKeys_.size();
        } else {
          return oneTimePreKeysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public getOneTimePreKeys(int index) {
        if (oneTimePreKeysBuilder_ == null) {
          return oneTimePreKeys_.get(index);
        } else {
          return oneTimePreKeysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder setOneTimePreKeys(
          int index, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public value) {
        if (oneTimePreKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.set(index, value);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder setOneTimePreKeys(
          int index, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder builderForValue) {
        if (oneTimePreKeysBuilder_ == null) {
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.set(index, builderForValue.build());
          onChanged();
        } else {
          oneTimePreKeysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder addOneTimePreKeys(org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public value) {
        if (oneTimePreKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.add(value);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder addOneTimePreKeys(
          int index, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public value) {
        if (oneTimePreKeysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.add(index, value);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder addOneTimePreKeys(
          org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder builderForValue) {
        if (oneTimePreKeysBuilder_ == null) {
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.add(builderForValue.build());
          onChanged();
        } else {
          oneTimePreKeysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder addOneTimePreKeys(
          int index, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder builderForValue) {
        if (oneTimePreKeysBuilder_ == null) {
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.add(index, builderForValue.build());
          onChanged();
        } else {
          oneTimePreKeysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder addAllOneTimePreKeys(
          java.lang.Iterable<? extends org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public> values) {
        if (oneTimePreKeysBuilder_ == null) {
          ensureOneTimePreKeysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, oneTimePreKeys_);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder clearOneTimePreKeys() {
        if (oneTimePreKeysBuilder_ == null) {
          oneTimePreKeys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public Builder removeOneTimePreKeys(int index) {
        if (oneTimePreKeysBuilder_ == null) {
          ensureOneTimePreKeysIsMutable();
          oneTimePreKeys_.remove(index);
          onChanged();
        } else {
          oneTimePreKeysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder getOneTimePreKeysBuilder(
          int index) {
        return getOneTimePreKeysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder getOneTimePreKeysOrBuilder(
          int index) {
        if (oneTimePreKeysBuilder_ == null) {
          return oneTimePreKeys_.get(index);  } else {
          return oneTimePreKeysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public java.util.List<? extends org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder> 
           getOneTimePreKeysOrBuilderList() {
        if (oneTimePreKeysBuilder_ != null) {
          return oneTimePreKeysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(oneTimePreKeys_);
        }
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder addOneTimePreKeysBuilder() {
        return getOneTimePreKeysFieldBuilder().addBuilder(
            org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.getDefaultInstance());
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder addOneTimePreKeysBuilder(
          int index) {
        return getOneTimePreKeysFieldBuilder().addBuilder(
            index, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.getDefaultInstance());
      }
      /**
       * <code>repeated .skissm.one_time_pre_key_public one_time_pre_keys = 7;</code>
       */
      public java.util.List<org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder> 
           getOneTimePreKeysBuilderList() {
        return getOneTimePreKeysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder> 
          getOneTimePreKeysFieldBuilder() {
        if (oneTimePreKeysBuilder_ == null) {
          oneTimePreKeysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_public.Builder, org.e2eelab.skissm.proto.OneTimePreKeyPublic.one_time_pre_key_publicOrBuilder>(
                  oneTimePreKeys_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          oneTimePreKeys_ = null;
        }
        return oneTimePreKeysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:skissm.register_user_request_payload)
    }

    // @@protoc_insertion_point(class_scope:skissm.register_user_request_payload)
    private static final org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload();
    }

    public static org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<register_user_request_payload>
        PARSER = new com.google.protobuf.AbstractParser<register_user_request_payload>() {
      @java.lang.Override
      public register_user_request_payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new register_user_request_payload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<register_user_request_payload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<register_user_request_payload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.e2eelab.skissm.proto.RegisterUserRequestPayload.register_user_request_payload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skissm_register_user_request_payload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_skissm_register_user_request_payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*skissm/register_user_request_payload.p" +
      "roto\022\006skissm\032\"skissm/signed_pre_key_publ" +
      "ic.proto\032$skissm/one_time_pre_key_public" +
      ".proto\"\206\002\n\035register_user_request_payload" +
      "\022\021\n\tuser_name\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\025" +
      "\n\rauthenticator\030\003 \001(\t\022\021\n\tauth_code\030\004 \001(\t" +
      "\022\033\n\023identity_key_public\030\005 \001(\014\022<\n\025signed_" +
      "pre_key_public\030\006 \001(\0132\035.skissm.signed_pre" +
      "_key_public\022:\n\021one_time_pre_keys\030\007 \003(\0132\037" +
      ".skissm.one_time_pre_key_publicB6\n\030org.e" +
      "2eelab.skissm.protoB\032RegisterUserRequest" +
      "Payloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.e2eelab.skissm.proto.SignedPreKeyPublic.getDescriptor(),
          org.e2eelab.skissm.proto.OneTimePreKeyPublic.getDescriptor(),
        });
    internal_static_skissm_register_user_request_payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_skissm_register_user_request_payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_skissm_register_user_request_payload_descriptor,
        new java.lang.String[] { "UserName", "DeviceId", "Authenticator", "AuthCode", "IdentityKeyPublic", "SignedPreKeyPublic", "OneTimePreKeys", });
    org.e2eelab.skissm.proto.SignedPreKeyPublic.getDescriptor();
    org.e2eelab.skissm.proto.OneTimePreKeyPublic.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
