/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chain_key.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chain_key.pb-c.h"
void   org__e2eelab__lib__protobuf__chain_key__init
                     (Org__E2eelab__Lib__Protobuf__ChainKey         *message)
{
  static const Org__E2eelab__Lib__Protobuf__ChainKey init_value = ORG__E2EELAB__LIB__PROTOBUF__CHAIN_KEY__INIT;
  *message = init_value;
}
size_t org__e2eelab__lib__protobuf__chain_key__get_packed_size
                     (const Org__E2eelab__Lib__Protobuf__ChainKey *message)
{
  assert(message->base.descriptor == &org__e2eelab__lib__protobuf__chain_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t org__e2eelab__lib__protobuf__chain_key__pack
                     (const Org__E2eelab__Lib__Protobuf__ChainKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &org__e2eelab__lib__protobuf__chain_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t org__e2eelab__lib__protobuf__chain_key__pack_to_buffer
                     (const Org__E2eelab__Lib__Protobuf__ChainKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &org__e2eelab__lib__protobuf__chain_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Org__E2eelab__Lib__Protobuf__ChainKey *
       org__e2eelab__lib__protobuf__chain_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Org__E2eelab__Lib__Protobuf__ChainKey *)
     protobuf_c_message_unpack (&org__e2eelab__lib__protobuf__chain_key__descriptor,
                                allocator, len, data);
}
void   org__e2eelab__lib__protobuf__chain_key__free_unpacked
                     (Org__E2eelab__Lib__Protobuf__ChainKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &org__e2eelab__lib__protobuf__chain_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor org__e2eelab__lib__protobuf__chain_key__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Org__E2eelab__Lib__Protobuf__ChainKey, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shared_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Org__E2eelab__Lib__Protobuf__ChainKey, shared_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__e2eelab__lib__protobuf__chain_key__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = shared_key */
};
static const ProtobufCIntRange org__e2eelab__lib__protobuf__chain_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor org__e2eelab__lib__protobuf__chain_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.e2eelab.lib.protobuf.chain_key",
  "ChainKey",
  "Org__E2eelab__Lib__Protobuf__ChainKey",
  "org.e2eelab.lib.protobuf",
  sizeof(Org__E2eelab__Lib__Protobuf__ChainKey),
  2,
  org__e2eelab__lib__protobuf__chain_key__field_descriptors,
  org__e2eelab__lib__protobuf__chain_key__field_indices_by_name,
  1,  org__e2eelab__lib__protobuf__chain_key__number_ranges,
  (ProtobufCMessageInit) org__e2eelab__lib__protobuf__chain_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
