/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: e2ee_address.proto */

#ifndef PROTOBUF_C_e2ee_5faddress_2eproto__INCLUDED
#define PROTOBUF_C_e2ee_5faddress_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Org__E2eelab__Lib__Protobuf__E2eeAddress Org__E2eelab__Lib__Protobuf__E2eeAddress;


/* --- enums --- */


/* --- messages --- */

struct  _Org__E2eelab__Lib__Protobuf__E2eeAddress
{
  ProtobufCMessage base;
  ProtobufCBinaryData domain;
  ProtobufCBinaryData user_id;
  ProtobufCBinaryData device_id;
  ProtobufCBinaryData group_id;
};
#define ORG__E2EELAB__LIB__PROTOBUF__E2EE_ADDRESS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__e2eelab__lib__protobuf__e2ee_address__descriptor) \
    , {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


/* Org__E2eelab__Lib__Protobuf__E2eeAddress methods */
void   org__e2eelab__lib__protobuf__e2ee_address__init
                     (Org__E2eelab__Lib__Protobuf__E2eeAddress         *message);
size_t org__e2eelab__lib__protobuf__e2ee_address__get_packed_size
                     (const Org__E2eelab__Lib__Protobuf__E2eeAddress   *message);
size_t org__e2eelab__lib__protobuf__e2ee_address__pack
                     (const Org__E2eelab__Lib__Protobuf__E2eeAddress   *message,
                      uint8_t             *out);
size_t org__e2eelab__lib__protobuf__e2ee_address__pack_to_buffer
                     (const Org__E2eelab__Lib__Protobuf__E2eeAddress   *message,
                      ProtobufCBuffer     *buffer);
Org__E2eelab__Lib__Protobuf__E2eeAddress *
       org__e2eelab__lib__protobuf__e2ee_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   org__e2eelab__lib__protobuf__e2ee_address__free_unpacked
                     (Org__E2eelab__Lib__Protobuf__E2eeAddress *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Org__E2eelab__Lib__Protobuf__E2eeAddress_Closure)
                 (const Org__E2eelab__Lib__Protobuf__E2eeAddress *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor org__e2eelab__lib__protobuf__e2ee_address__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_e2ee_5faddress_2eproto__INCLUDED */
