/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: skissm/service/dto/connect_request.proto */

#ifndef PROTOBUF_C_skissm_2fservice_2fdto_2fconnect_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_skissm_2fservice_2fdto_2fconnect_5frequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Org__E2eelab__Server__Grpc__ConnectRequest Org__E2eelab__Server__Grpc__ConnectRequest;


/* --- enums --- */


/* --- messages --- */

struct  Org__E2eelab__Server__Grpc__ConnectRequest
{
  ProtobufCMessage base;
  char *access_token;
};
#define ORG__E2EELAB__SERVER__GRPC__CONNECT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__e2eelab__server__grpc__connect_request__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Org__E2eelab__Server__Grpc__ConnectRequest methods */
void   org__e2eelab__server__grpc__connect_request__init
                     (Org__E2eelab__Server__Grpc__ConnectRequest         *message);
size_t org__e2eelab__server__grpc__connect_request__get_packed_size
                     (const Org__E2eelab__Server__Grpc__ConnectRequest   *message);
size_t org__e2eelab__server__grpc__connect_request__pack
                     (const Org__E2eelab__Server__Grpc__ConnectRequest   *message,
                      uint8_t             *out);
size_t org__e2eelab__server__grpc__connect_request__pack_to_buffer
                     (const Org__E2eelab__Server__Grpc__ConnectRequest   *message,
                      ProtobufCBuffer     *buffer);
Org__E2eelab__Server__Grpc__ConnectRequest *
       org__e2eelab__server__grpc__connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   org__e2eelab__server__grpc__connect_request__free_unpacked
                     (Org__E2eelab__Server__Grpc__ConnectRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Org__E2eelab__Server__Grpc__ConnectRequest_Closure)
                 (const Org__E2eelab__Server__Grpc__ConnectRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor org__e2eelab__server__grpc__connect_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_skissm_2fservice_2fdto_2fconnect_5frequest_2eproto__INCLUDED */
