/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: skissm/e2ee_group_session.proto */

#ifndef PROTOBUF_C_skissm_2fe2ee_5fgroup_5fsession_2eproto__INCLUDED
#define PROTOBUF_C_skissm_2fe2ee_5fgroup_5fsession_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "skissm/e2ee_address.pb-c.h"

typedef struct Org__E2eelab__Skissm__Proto__E2eeGroupSession Org__E2eelab__Skissm__Proto__E2eeGroupSession;


/* --- enums --- */


/* --- messages --- */

struct  Org__E2eelab__Skissm__Proto__E2eeGroupSession
{
  ProtobufCMessage base;
  uint32_t version;
  ProtobufCBinaryData session_id;
  Org__E2eelab__Skissm__Proto__E2eeAddress *session_owner;
  Org__E2eelab__Skissm__Proto__E2eeAddress *group_address;
  size_t n_member_addresses;
  Org__E2eelab__Skissm__Proto__E2eeAddress **member_addresses;
  uint32_t sequence;
  ProtobufCBinaryData chain_key;
  ProtobufCBinaryData signature_private_key;
  ProtobufCBinaryData signature_public_key;
  ProtobufCBinaryData associated_data;
};
#define ORG__E2EELAB__SKISSM__PROTO__E2EE_GROUP_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__e2eelab__skissm__proto__e2ee_group_session__descriptor) \
    , 0, {0,NULL}, NULL, NULL, 0,NULL, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


/* Org__E2eelab__Skissm__Proto__E2eeGroupSession methods */
void   org__e2eelab__skissm__proto__e2ee_group_session__init
                     (Org__E2eelab__Skissm__Proto__E2eeGroupSession         *message);
size_t org__e2eelab__skissm__proto__e2ee_group_session__get_packed_size
                     (const Org__E2eelab__Skissm__Proto__E2eeGroupSession   *message);
size_t org__e2eelab__skissm__proto__e2ee_group_session__pack
                     (const Org__E2eelab__Skissm__Proto__E2eeGroupSession   *message,
                      uint8_t             *out);
size_t org__e2eelab__skissm__proto__e2ee_group_session__pack_to_buffer
                     (const Org__E2eelab__Skissm__Proto__E2eeGroupSession   *message,
                      ProtobufCBuffer     *buffer);
Org__E2eelab__Skissm__Proto__E2eeGroupSession *
       org__e2eelab__skissm__proto__e2ee_group_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   org__e2eelab__skissm__proto__e2ee_group_session__free_unpacked
                     (Org__E2eelab__Skissm__Proto__E2eeGroupSession *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Org__E2eelab__Skissm__Proto__E2eeGroupSession_Closure)
                 (const Org__E2eelab__Skissm__Proto__E2eeGroupSession *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor org__e2eelab__skissm__proto__e2ee_group_session__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_skissm_2fe2ee_5fgroup_5fsession_2eproto__INCLUDED */
