/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: skissm/e2ee_commands.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "skissm/e2ee_commands.pb-c.h"
static const ProtobufCEnumValue org__e2eelab__skissm__proto__e2ee_commands__enum_values_by_number[22] =
{
  { "register_user_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__register_user_request", 0 },
  { "delete_user_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__delete_user_request", 2 },
  { "get_pre_key_bundle", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__get_pre_key_bundle", 4 },
  { "publish_spk_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__publish_spk_request", 6 },
  { "supply_opks_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__supply_opks_request", 8 },
  { "create_group_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__create_group_request", 10 },
  { "get_group_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__get_group_request", 12 },
  { "add_group_members_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__add_group_members_request", 14 },
  { "remove_group_members_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__remove_group_members_request", 16 },
  { "send_one2one_msg_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__send_one2one_msg_request", 18 },
  { "send_group_msg_request", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__send_group_msg_request", 20 },
  { "register_user_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__register_user_response", 4097 },
  { "delete_user_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__delete_user_response", 4099 },
  { "get_pre_key_bundle_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__get_pre_key_bundle_response", 4101 },
  { "publish_spk_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__publish_spk_response", 4103 },
  { "supply_opks_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__supply_opks_response", 4105 },
  { "create_group_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__create_group_response", 4107 },
  { "get_group_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__get_group_response", 4109 },
  { "add_group_members_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__add_group_members_response", 4111 },
  { "remove_group_members_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__remove_group_members_response", 4113 },
  { "send_one2one_msg_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__send_one2one_msg_response", 4115 },
  { "send_group_msg_response", "ORG__E2EELAB__SKISSM__PROTO__E2EE_COMMANDS__send_group_msg_response", 4117 },
};
static const ProtobufCIntRange org__e2eelab__skissm__proto__e2ee_commands__value_ranges[] = {
{0, 0},{2, 1},{4, 2},{6, 3},{8, 4},{10, 5},{12, 6},{14, 7},{16, 8},{18, 9},{20, 10},{4097, 11},{4099, 12},{4101, 13},{4103, 14},{4105, 15},{4107, 16},{4109, 17},{4111, 18},{4113, 19},{4115, 20},{4117, 21},{0, 22}
};
static const ProtobufCEnumValueIndex org__e2eelab__skissm__proto__e2ee_commands__enum_values_by_name[22] =
{
  { "add_group_members_request", 7 },
  { "add_group_members_response", 18 },
  { "create_group_request", 5 },
  { "create_group_response", 16 },
  { "delete_user_request", 1 },
  { "delete_user_response", 12 },
  { "get_group_request", 6 },
  { "get_group_response", 17 },
  { "get_pre_key_bundle", 2 },
  { "get_pre_key_bundle_response", 13 },
  { "publish_spk_request", 3 },
  { "publish_spk_response", 14 },
  { "register_user_request", 0 },
  { "register_user_response", 11 },
  { "remove_group_members_request", 8 },
  { "remove_group_members_response", 19 },
  { "send_group_msg_request", 10 },
  { "send_group_msg_response", 21 },
  { "send_one2one_msg_request", 9 },
  { "send_one2one_msg_response", 20 },
  { "supply_opks_request", 4 },
  { "supply_opks_response", 15 },
};
const ProtobufCEnumDescriptor org__e2eelab__skissm__proto__e2ee_commands__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "org.e2eelab.skissm.proto.e2ee_commands",
  "e2ee_commands",
  "Org__E2eelab__Skissm__Proto__E2eeCommands",
  "org.e2eelab.skissm.proto",
  22,
  org__e2eelab__skissm__proto__e2ee_commands__enum_values_by_number,
  22,
  org__e2eelab__skissm__proto__e2ee_commands__enum_values_by_name,
  22,
  org__e2eelab__skissm__proto__e2ee_commands__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
