/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AddGroupMembersResponse.proto */

#ifndef PROTOBUF_C_AddGroupMembersResponse_2eproto__INCLUDED
#define PROTOBUF_C_AddGroupMembersResponse_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "skissm/GroupMember.pb-c.h"

typedef struct Skissm__AddGroupMembersResponse Skissm__AddGroupMembersResponse;


/* --- enums --- */


/* --- messages --- */

struct  Skissm__AddGroupMembersResponse
{
  ProtobufCMessage base;
  uint32_t code;
  char *msg;
  size_t n_group_members;
  Skissm__GroupMember **group_members;
};
#define SKISSM__ADD_GROUP_MEMBERS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&skissm__add_group_members_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Skissm__AddGroupMembersResponse methods */
void   skissm__add_group_members_response__init
                     (Skissm__AddGroupMembersResponse         *message);
size_t skissm__add_group_members_response__get_packed_size
                     (const Skissm__AddGroupMembersResponse   *message);
size_t skissm__add_group_members_response__pack
                     (const Skissm__AddGroupMembersResponse   *message,
                      uint8_t             *out);
size_t skissm__add_group_members_response__pack_to_buffer
                     (const Skissm__AddGroupMembersResponse   *message,
                      ProtobufCBuffer     *buffer);
Skissm__AddGroupMembersResponse *
       skissm__add_group_members_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   skissm__add_group_members_response__free_unpacked
                     (Skissm__AddGroupMembersResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Skissm__AddGroupMembersResponse_Closure)
                 (const Skissm__AddGroupMembersResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor skissm__add_group_members_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AddGroupMembersResponse_2eproto__INCLUDED */
