/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CreateGroupRequest.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CreateGroupRequest.pb-c.h"
void   skissm__create_group_request__init
                     (Skissm__CreateGroupRequest         *message)
{
  static const Skissm__CreateGroupRequest init_value = SKISSM__CREATE_GROUP_REQUEST__INIT;
  *message = init_value;
}
size_t skissm__create_group_request__get_packed_size
                     (const Skissm__CreateGroupRequest *message)
{
  assert(message->base.descriptor == &skissm__create_group_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__create_group_request__pack
                     (const Skissm__CreateGroupRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__create_group_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__create_group_request__pack_to_buffer
                     (const Skissm__CreateGroupRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__create_group_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__CreateGroupRequest *
       skissm__create_group_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__CreateGroupRequest *)
     protobuf_c_message_unpack (&skissm__create_group_request__descriptor,
                                allocator, len, data);
}
void   skissm__create_group_request__free_unpacked
                     (Skissm__CreateGroupRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__create_group_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__create_group_request__field_descriptors[1] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__CreateGroupRequest, msg),
    &skissm__create_group_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__create_group_request__field_indices_by_name[] = {
  0,   /* field[0] = msg */
};
static const ProtobufCIntRange skissm__create_group_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor skissm__create_group_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.CreateGroupRequest",
  "CreateGroupRequest",
  "Skissm__CreateGroupRequest",
  "skissm",
  sizeof(Skissm__CreateGroupRequest),
  1,
  skissm__create_group_request__field_descriptors,
  skissm__create_group_request__field_indices_by_name,
  1,  skissm__create_group_request__number_ranges,
  (ProtobufCMessageInit) skissm__create_group_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
