/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: GroupMsgPayload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "GroupMsgPayload.pb-c.h"
void   skissm__group_msg_payload__init
                     (Skissm__GroupMsgPayload         *message)
{
  static const Skissm__GroupMsgPayload init_value = SKISSM__GROUP_MSG_PAYLOAD__INIT;
  *message = init_value;
}
size_t skissm__group_msg_payload__get_packed_size
                     (const Skissm__GroupMsgPayload *message)
{
  assert(message->base.descriptor == &skissm__group_msg_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__group_msg_payload__pack
                     (const Skissm__GroupMsgPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__group_msg_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__group_msg_payload__pack_to_buffer
                     (const Skissm__GroupMsgPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__group_msg_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__GroupMsgPayload *
       skissm__group_msg_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__GroupMsgPayload *)
     protobuf_c_message_unpack (&skissm__group_msg_payload__descriptor,
                                allocator, len, data);
}
void   skissm__group_msg_payload__free_unpacked
                     (Skissm__GroupMsgPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__group_msg_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__group_msg_payload__field_descriptors[3] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Skissm__GroupMsgPayload, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciphertext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Skissm__GroupMsgPayload, ciphertext),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Skissm__GroupMsgPayload, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__group_msg_payload__field_indices_by_name[] = {
  1,   /* field[1] = ciphertext */
  0,   /* field[0] = sequence */
  2,   /* field[2] = signature */
};
static const ProtobufCIntRange skissm__group_msg_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor skissm__group_msg_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.GroupMsgPayload",
  "GroupMsgPayload",
  "Skissm__GroupMsgPayload",
  "skissm",
  sizeof(Skissm__GroupMsgPayload),
  3,
  skissm__group_msg_payload__field_descriptors,
  skissm__group_msg_payload__field_indices_by_name,
  1,  skissm__group_msg_payload__number_ranges,
  (ProtobufCMessageInit) skissm__group_msg_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
