/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ProtoMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ProtoMsg.pb-c.h"
void   skissm__proto_msg__init
                     (Skissm__ProtoMsg         *message)
{
  static const Skissm__ProtoMsg init_value = SKISSM__PROTO_MSG__INIT;
  *message = init_value;
}
size_t skissm__proto_msg__get_packed_size
                     (const Skissm__ProtoMsg *message)
{
  assert(message->base.descriptor == &skissm__proto_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__proto_msg__pack
                     (const Skissm__ProtoMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__proto_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__proto_msg__pack_to_buffer
                     (const Skissm__ProtoMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__proto_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__ProtoMsg *
       skissm__proto_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__ProtoMsg *)
     protobuf_c_message_unpack (&skissm__proto_msg__descriptor,
                                allocator, len, data);
}
void   skissm__proto_msg__free_unpacked
                     (Skissm__ProtoMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__proto_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__proto_msg__field_descriptors[11] =
{
  {
    "proto_msg_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Skissm__ProtoMsg, proto_msg_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__ProtoMsg, from),
    &skissm__e2ee_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__ProtoMsg, to),
    &skissm__e2ee_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accept_msg",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, accept_msg),
    &skissm__accept_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_group_members_msg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, add_group_members_msg),
    &skissm__add_group_members_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_group_msg",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, create_group_msg),
    &skissm__create_group_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e2ee_msg",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, e2ee_msg),
    &skissm__e2ee_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invite_msg",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, invite_msg),
    &skissm__invite_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remove_group_members_msg",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, remove_group_members_msg),
    &skissm__remove_group_members_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supply_opks_msg",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, supply_opks_msg),
    &skissm__supply_opks_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat_msg",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__ProtoMsg, payload_case),
    offsetof(Skissm__ProtoMsg, heartbeat_msg),
    &skissm__heartbeat_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__proto_msg__field_indices_by_name[] = {
  3,   /* field[3] = accept_msg */
  4,   /* field[4] = add_group_members_msg */
  5,   /* field[5] = create_group_msg */
  6,   /* field[6] = e2ee_msg */
  1,   /* field[1] = from */
  10,   /* field[10] = heartbeat_msg */
  7,   /* field[7] = invite_msg */
  0,   /* field[0] = proto_msg_id */
  8,   /* field[8] = remove_group_members_msg */
  9,   /* field[9] = supply_opks_msg */
  2,   /* field[2] = to */
};
static const ProtobufCIntRange skissm__proto_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor skissm__proto_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.ProtoMsg",
  "ProtoMsg",
  "Skissm__ProtoMsg",
  "skissm",
  sizeof(Skissm__ProtoMsg),
  11,
  skissm__proto_msg__field_descriptors,
  skissm__proto_msg__field_indices_by_name,
  1,  skissm__proto_msg__number_ranges,
  (ProtobufCMessageInit) skissm__proto_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
