/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ReceiverChainNode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ReceiverChainNode.pb-c.h"
void   skissm__receiver_chain_node__init
                     (Skissm__ReceiverChainNode         *message)
{
  static const Skissm__ReceiverChainNode init_value = SKISSM__RECEIVER_CHAIN_NODE__INIT;
  *message = init_value;
}
size_t skissm__receiver_chain_node__get_packed_size
                     (const Skissm__ReceiverChainNode *message)
{
  assert(message->base.descriptor == &skissm__receiver_chain_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__receiver_chain_node__pack
                     (const Skissm__ReceiverChainNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__receiver_chain_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__receiver_chain_node__pack_to_buffer
                     (const Skissm__ReceiverChainNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__receiver_chain_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__ReceiverChainNode *
       skissm__receiver_chain_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__ReceiverChainNode *)
     protobuf_c_message_unpack (&skissm__receiver_chain_node__descriptor,
                                allocator, len, data);
}
void   skissm__receiver_chain_node__free_unpacked
                     (Skissm__ReceiverChainNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__receiver_chain_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__receiver_chain_node__field_descriptors[2] =
{
  {
    "ratchet_key_public",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Skissm__ReceiverChainNode, ratchet_key_public),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chain_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__ReceiverChainNode, chain_key),
    &skissm__chain_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__receiver_chain_node__field_indices_by_name[] = {
  1,   /* field[1] = chain_key */
  0,   /* field[0] = ratchet_key_public */
};
static const ProtobufCIntRange skissm__receiver_chain_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor skissm__receiver_chain_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.ReceiverChainNode",
  "ReceiverChainNode",
  "Skissm__ReceiverChainNode",
  "skissm",
  sizeof(Skissm__ReceiverChainNode),
  2,
  skissm__receiver_chain_node__field_descriptors,
  skissm__receiver_chain_node__field_indices_by_name,
  1,  skissm__receiver_chain_node__number_ranges,
  (ProtobufCMessageInit) skissm__receiver_chain_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
