/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RemoveGroupMembersMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "RemoveGroupMembersMsg.pb-c.h"
void   skissm__remove_group_members_msg__init
                     (Skissm__RemoveGroupMembersMsg         *message)
{
  static const Skissm__RemoveGroupMembersMsg init_value = SKISSM__REMOVE_GROUP_MEMBERS_MSG__INIT;
  *message = init_value;
}
size_t skissm__remove_group_members_msg__get_packed_size
                     (const Skissm__RemoveGroupMembersMsg *message)
{
  assert(message->base.descriptor == &skissm__remove_group_members_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__remove_group_members_msg__pack
                     (const Skissm__RemoveGroupMembersMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__remove_group_members_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__remove_group_members_msg__pack_to_buffer
                     (const Skissm__RemoveGroupMembersMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__remove_group_members_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__RemoveGroupMembersMsg *
       skissm__remove_group_members_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__RemoveGroupMembersMsg *)
     protobuf_c_message_unpack (&skissm__remove_group_members_msg__descriptor,
                                allocator, len, data);
}
void   skissm__remove_group_members_msg__free_unpacked
                     (Skissm__RemoveGroupMembersMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__remove_group_members_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__remove_group_members_msg__field_descriptors[5] =
{
  {
    "e2ee_pack_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Skissm__RemoveGroupMembersMsg, e2ee_pack_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__RemoveGroupMembersMsg, sender_address),
    &skissm__e2ee_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Skissm__RemoveGroupMembersMsg, group_address),
    &skissm__e2ee_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "removing_members",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__RemoveGroupMembersMsg, n_removing_members),
    offsetof(Skissm__RemoveGroupMembersMsg, removing_members),
    &skissm__group_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_members",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Skissm__RemoveGroupMembersMsg, n_all_members),
    offsetof(Skissm__RemoveGroupMembersMsg, all_members),
    &skissm__group_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__remove_group_members_msg__field_indices_by_name[] = {
  4,   /* field[4] = all_members */
  0,   /* field[0] = e2ee_pack_id */
  2,   /* field[2] = group_address */
  3,   /* field[3] = removing_members */
  1,   /* field[1] = sender_address */
};
static const ProtobufCIntRange skissm__remove_group_members_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor skissm__remove_group_members_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.RemoveGroupMembersMsg",
  "RemoveGroupMembersMsg",
  "Skissm__RemoveGroupMembersMsg",
  "skissm",
  sizeof(Skissm__RemoveGroupMembersMsg),
  5,
  skissm__remove_group_members_msg__field_descriptors,
  skissm__remove_group_members_msg__field_indices_by_name,
  1,  skissm__remove_group_members_msg__number_ranges,
  (ProtobufCMessageInit) skissm__remove_group_members_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
