/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SignedPreKeyPublic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SignedPreKeyPublic.pb-c.h"
void   skissm__signed_pre_key_public__init
                     (Skissm__SignedPreKeyPublic         *message)
{
  static const Skissm__SignedPreKeyPublic init_value = SKISSM__SIGNED_PRE_KEY_PUBLIC__INIT;
  *message = init_value;
}
size_t skissm__signed_pre_key_public__get_packed_size
                     (const Skissm__SignedPreKeyPublic *message)
{
  assert(message->base.descriptor == &skissm__signed_pre_key_public__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skissm__signed_pre_key_public__pack
                     (const Skissm__SignedPreKeyPublic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skissm__signed_pre_key_public__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skissm__signed_pre_key_public__pack_to_buffer
                     (const Skissm__SignedPreKeyPublic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skissm__signed_pre_key_public__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Skissm__SignedPreKeyPublic *
       skissm__signed_pre_key_public__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Skissm__SignedPreKeyPublic *)
     protobuf_c_message_unpack (&skissm__signed_pre_key_public__descriptor,
                                allocator, len, data);
}
void   skissm__signed_pre_key_public__free_unpacked
                     (Skissm__SignedPreKeyPublic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skissm__signed_pre_key_public__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor skissm__signed_pre_key_public__field_descriptors[3] =
{
  {
    "spk_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Skissm__SignedPreKeyPublic, spk_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Skissm__SignedPreKeyPublic, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Skissm__SignedPreKeyPublic, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skissm__signed_pre_key_public__field_indices_by_name[] = {
  1,   /* field[1] = public_key */
  2,   /* field[2] = signature */
  0,   /* field[0] = spk_id */
};
static const ProtobufCIntRange skissm__signed_pre_key_public__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor skissm__signed_pre_key_public__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "skissm.SignedPreKeyPublic",
  "SignedPreKeyPublic",
  "Skissm__SignedPreKeyPublic",
  "skissm",
  sizeof(Skissm__SignedPreKeyPublic),
  3,
  skissm__signed_pre_key_public__field_descriptors,
  skissm__signed_pre_key_public__field_indices_by_name,
  1,  skissm__signed_pre_key_public__number_ranges,
  (ProtobufCMessageInit) skissm__signed_pre_key_public__init,
  NULL,NULL,NULL    /* reserved[123] */
};
