// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skiserver/acquire_server_info_response.proto

package org.e2eelab.skiserver.proto;

public final class AcquireServerInfoResponse {
  private AcquireServerInfoResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface acquire_server_info_responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skiserver.acquire_server_info_response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hostname = 1;</code>
     * @return The hostname.
     */
    java.lang.String getHostname();
    /**
     * <code>string hostname = 1;</code>
     * @return The bytes for hostname.
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    /**
     * <code>int64 server_t = 2;</code>
     * @return The serverT.
     */
    long getServerT();
  }
  /**
   * Protobuf type {@code skiserver.acquire_server_info_response}
   */
  public static final class acquire_server_info_response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:skiserver.acquire_server_info_response)
      acquire_server_info_responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use acquire_server_info_response.newBuilder() to construct.
    private acquire_server_info_response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private acquire_server_info_response() {
      hostname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new acquire_server_info_response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private acquire_server_info_response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hostname_ = s;
              break;
            }
            case 16: {

              serverT_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.internal_static_skiserver_acquire_server_info_response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.internal_static_skiserver_acquire_server_info_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.class, org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.Builder.class);
    }

    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object hostname_;
    /**
     * <code>string hostname = 1;</code>
     * @return The hostname.
     */
    @java.lang.Override
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      }
    }
    /**
     * <code>string hostname = 1;</code>
     * @return The bytes for hostname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_T_FIELD_NUMBER = 2;
    private long serverT_;
    /**
     * <code>int64 server_t = 2;</code>
     * @return The serverT.
     */
    @java.lang.Override
    public long getServerT() {
      return serverT_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostname_);
      }
      if (serverT_ != 0L) {
        output.writeInt64(2, serverT_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostname_);
      }
      if (serverT_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverT_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response)) {
        return super.equals(obj);
      }
      org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response other = (org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response) obj;

      if (!getHostname()
          .equals(other.getHostname())) return false;
      if (getServerT()
          != other.getServerT()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostname().hashCode();
      hash = (37 * hash) + SERVER_T_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerT());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code skiserver.acquire_server_info_response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:skiserver.acquire_server_info_response)
        org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.internal_static_skiserver_acquire_server_info_response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.internal_static_skiserver_acquire_server_info_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.class, org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.Builder.class);
      }

      // Construct using org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hostname_ = "";

        serverT_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.internal_static_skiserver_acquire_server_info_response_descriptor;
      }

      @java.lang.Override
      public org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response getDefaultInstanceForType() {
        return org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.getDefaultInstance();
      }

      @java.lang.Override
      public org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response build() {
        org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response buildPartial() {
        org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response result = new org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response(this);
        result.hostname_ = hostname_;
        result.serverT_ = serverT_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response) {
          return mergeFrom((org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response other) {
        if (other == org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response.getDefaultInstance()) return this;
        if (!other.getHostname().isEmpty()) {
          hostname_ = other.hostname_;
          onChanged();
        }
        if (other.getServerT() != 0L) {
          setServerT(other.getServerT());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hostname_ = "";
      /**
       * <code>string hostname = 1;</code>
       * @return The hostname.
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostname = 1;</code>
       * @return The bytes for hostname.
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostname = 1;</code>
       * @param value The hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostname() {
        
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      /**
       * <code>string hostname = 1;</code>
       * @param value The bytes for hostname to set.
       * @return This builder for chaining.
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostname_ = value;
        onChanged();
        return this;
      }

      private long serverT_ ;
      /**
       * <code>int64 server_t = 2;</code>
       * @return The serverT.
       */
      @java.lang.Override
      public long getServerT() {
        return serverT_;
      }
      /**
       * <code>int64 server_t = 2;</code>
       * @param value The serverT to set.
       * @return This builder for chaining.
       */
      public Builder setServerT(long value) {
        
        serverT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 server_t = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerT() {
        
        serverT_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:skiserver.acquire_server_info_response)
    }

    // @@protoc_insertion_point(class_scope:skiserver.acquire_server_info_response)
    private static final org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response();
    }

    public static org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<acquire_server_info_response>
        PARSER = new com.google.protobuf.AbstractParser<acquire_server_info_response>() {
      @java.lang.Override
      public acquire_server_info_response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new acquire_server_info_response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<acquire_server_info_response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<acquire_server_info_response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.e2eelab.skiserver.proto.AcquireServerInfoResponse.acquire_server_info_response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skiserver_acquire_server_info_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_skiserver_acquire_server_info_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,skiserver/acquire_server_info_response" +
      ".proto\022\tskiserver\"B\n\034acquire_server_info" +
      "_response\022\020\n\010hostname\030\001 \001(\t\022\020\n\010server_t\030" +
      "\002 \001(\003B\035\n\033org.e2eelab.skiserver.protob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_skiserver_acquire_server_info_response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_skiserver_acquire_server_info_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_skiserver_acquire_server_info_response_descriptor,
        new java.lang.String[] { "Hostname", "ServerT", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
