// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: e2ee_message.proto

package org.e2eelab.skissm.proto;

public final class E2eeMessage {
  private E2eeMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface e2ee_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.e2eelab.skissm.proto.e2ee_message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     * @return Whether the from field is set.
     */
    boolean hasFrom();
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     * @return The from.
     */
    org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getFrom();
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     */
    org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getFromOrBuilder();

    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     * @return Whether the to field is set.
     */
    boolean hasTo();
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     * @return The to.
     */
    org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getTo();
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     */
    org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getToOrBuilder();

    /**
     * <code>bytes session_id = 4;</code>
     * @return The sessionId.
     */
    com.google.protobuf.ByteString getSessionId();

    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
     * @return The msgType.
     */
    org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type getMsgType();

    /**
     * <code>bytes payload = 6;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code org.e2eelab.skissm.proto.e2ee_message}
   */
  public static final class e2ee_message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.e2eelab.skissm.proto.e2ee_message)
      e2ee_messageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use e2ee_message.newBuilder() to construct.
    private e2ee_message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private e2ee_message() {
      sessionId_ = com.google.protobuf.ByteString.EMPTY;
      msgType_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new e2ee_message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private e2ee_message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 18: {
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder subBuilder = null;
              if (from_ != null) {
                subBuilder = from_.toBuilder();
              }
              from_ = input.readMessage(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(from_);
                from_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder subBuilder = null;
              if (to_ != null) {
                subBuilder = to_.toBuilder();
              }
              to_ = input.readMessage(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(to_);
                to_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {

              sessionId_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 50: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.e2eelab.skissm.proto.E2eeMessage.internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.e2eelab.skissm.proto.E2eeMessage.internal_static_org_e2eelab_skissm_proto_e2ee_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.class, org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private org.e2eelab.skissm.proto.E2eeAddress.e2ee_address from_;
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     * @return Whether the from field is set.
     */
    @java.lang.Override
    public boolean hasFrom() {
      return from_ != null;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     * @return The from.
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getFrom() {
      return from_ == null ? org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : from_;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getFromOrBuilder() {
      return getFrom();
    }

    public static final int TO_FIELD_NUMBER = 3;
    private org.e2eelab.skissm.proto.E2eeAddress.e2ee_address to_;
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     * @return Whether the to field is set.
     */
    @java.lang.Override
    public boolean hasTo() {
      return to_ != null;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getTo() {
      return to_ == null ? org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : to_;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getToOrBuilder() {
      return getTo();
    }

    public static final int SESSION_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString sessionId_;
    /**
     * <code>bytes session_id = 4;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionId() {
      return sessionId_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
     * @return The msgType.
     */
    @java.lang.Override public org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type getMsgType() {
      @SuppressWarnings("deprecation")
      org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type result = org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.valueOf(msgType_);
      return result == null ? org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 6;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (from_ != null) {
        output.writeMessage(2, getFrom());
      }
      if (to_ != null) {
        output.writeMessage(3, getTo());
      }
      if (!sessionId_.isEmpty()) {
        output.writeBytes(4, sessionId_);
      }
      if (msgType_ != org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.PRE_KEY.getNumber()) {
        output.writeEnum(5, msgType_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(6, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (from_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFrom());
      }
      if (to_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTo());
      }
      if (!sessionId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, sessionId_);
      }
      if (msgType_ != org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.PRE_KEY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.e2eelab.skissm.proto.E2eeMessage.e2ee_message)) {
        return super.equals(obj);
      }
      org.e2eelab.skissm.proto.E2eeMessage.e2ee_message other = (org.e2eelab.skissm.proto.E2eeMessage.e2ee_message) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (!getFrom()
            .equals(other.getFrom())) return false;
      }
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.e2eelab.skissm.proto.E2eeMessage.e2ee_message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.e2eelab.skissm.proto.e2ee_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.e2eelab.skissm.proto.e2ee_message)
        org.e2eelab.skissm.proto.E2eeMessage.e2ee_messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.e2eelab.skissm.proto.E2eeMessage.internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.e2eelab.skissm.proto.E2eeMessage.internal_static_org_e2eelab_skissm_proto_e2ee_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.class, org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.Builder.class);
      }

      // Construct using org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        if (fromBuilder_ == null) {
          from_ = null;
        } else {
          from_ = null;
          fromBuilder_ = null;
        }
        if (toBuilder_ == null) {
          to_ = null;
        } else {
          to_ = null;
          toBuilder_ = null;
        }
        sessionId_ = com.google.protobuf.ByteString.EMPTY;

        msgType_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.e2eelab.skissm.proto.E2eeMessage.internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.E2eeMessage.e2ee_message getDefaultInstanceForType() {
        return org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.getDefaultInstance();
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.E2eeMessage.e2ee_message build() {
        org.e2eelab.skissm.proto.E2eeMessage.e2ee_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.E2eeMessage.e2ee_message buildPartial() {
        org.e2eelab.skissm.proto.E2eeMessage.e2ee_message result = new org.e2eelab.skissm.proto.E2eeMessage.e2ee_message(this);
        result.version_ = version_;
        if (fromBuilder_ == null) {
          result.from_ = from_;
        } else {
          result.from_ = fromBuilder_.build();
        }
        if (toBuilder_ == null) {
          result.to_ = to_;
        } else {
          result.to_ = toBuilder_.build();
        }
        result.sessionId_ = sessionId_;
        result.msgType_ = msgType_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.e2eelab.skissm.proto.E2eeMessage.e2ee_message) {
          return mergeFrom((org.e2eelab.skissm.proto.E2eeMessage.e2ee_message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.e2eelab.skissm.proto.E2eeMessage.e2ee_message other) {
        if (other == org.e2eelab.skissm.proto.E2eeMessage.e2ee_message.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (other.hasTo()) {
          mergeTo(other.getTo());
        }
        if (other.getSessionId() != com.google.protobuf.ByteString.EMPTY) {
          setSessionId(other.getSessionId());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.e2eelab.skissm.proto.E2eeMessage.e2ee_message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.e2eelab.skissm.proto.E2eeMessage.e2ee_message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private org.e2eelab.skissm.proto.E2eeAddress.e2ee_address from_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder> fromBuilder_;
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       * @return Whether the from field is set.
       */
      public boolean hasFrom() {
        return fromBuilder_ != null || from_ != null;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       * @return The from.
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getFrom() {
        if (fromBuilder_ == null) {
          return from_ == null ? org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public Builder setFrom(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
          onChanged();
        } else {
          fromBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public Builder setFrom(
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
          onChanged();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public Builder mergeFrom(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address value) {
        if (fromBuilder_ == null) {
          if (from_ != null) {
            from_ =
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.newBuilder(from_).mergeFrom(value).buildPartial();
          } else {
            from_ = value;
          }
          onChanged();
        } else {
          fromBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public Builder clearFrom() {
        if (fromBuilder_ == null) {
          from_ = null;
          onChanged();
        } else {
          from_ = null;
          fromBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder getFromBuilder() {
        
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_ == null ?
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : from_;
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address from = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder>(
                  getFrom(),
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }

      private org.e2eelab.skissm.proto.E2eeAddress.e2ee_address to_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder> toBuilder_;
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       * @return Whether the to field is set.
       */
      public boolean hasTo() {
        return toBuilder_ != null || to_ != null;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       * @return The to.
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address getTo() {
        if (toBuilder_ == null) {
          return to_ == null ? org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : to_;
        } else {
          return toBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public Builder setTo(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          to_ = value;
          onChanged();
        } else {
          toBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public Builder setTo(
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder builderForValue) {
        if (toBuilder_ == null) {
          to_ = builderForValue.build();
          onChanged();
        } else {
          toBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public Builder mergeTo(org.e2eelab.skissm.proto.E2eeAddress.e2ee_address value) {
        if (toBuilder_ == null) {
          if (to_ != null) {
            to_ =
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.newBuilder(to_).mergeFrom(value).buildPartial();
          } else {
            to_ = value;
          }
          onChanged();
        } else {
          toBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public Builder clearTo() {
        if (toBuilder_ == null) {
          to_ = null;
          onChanged();
        } else {
          to_ = null;
          toBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder getToBuilder() {
        
        onChanged();
        return getToFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      public org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder getToOrBuilder() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilder();
        } else {
          return to_ == null ?
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.getDefaultInstance() : to_;
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_address to = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.e2eelab.skissm.proto.E2eeAddress.e2ee_address, org.e2eelab.skissm.proto.E2eeAddress.e2ee_address.Builder, org.e2eelab.skissm.proto.E2eeAddress.e2ee_addressOrBuilder>(
                  getTo(),
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }

      private com.google.protobuf.ByteString sessionId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes session_id = 4;</code>
       * @return The sessionId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSessionId() {
        return sessionId_;
      }
      /**
       * <code>bytes session_id = 4;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes session_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @java.lang.Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type getMsgType() {
        @SuppressWarnings("deprecation")
        org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type result = org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.valueOf(msgType_);
        return result == null ? org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(org.e2eelab.skissm.proto.E2eeMessageType.e2ee_message_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.e2ee_message_type msg_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 6;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 6;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.e2eelab.skissm.proto.e2ee_message)
    }

    // @@protoc_insertion_point(class_scope:org.e2eelab.skissm.proto.e2ee_message)
    private static final org.e2eelab.skissm.proto.E2eeMessage.e2ee_message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.e2eelab.skissm.proto.E2eeMessage.e2ee_message();
    }

    public static org.e2eelab.skissm.proto.E2eeMessage.e2ee_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<e2ee_message>
        PARSER = new com.google.protobuf.AbstractParser<e2ee_message>() {
      @java.lang.Override
      public e2ee_message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new e2ee_message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<e2ee_message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<e2ee_message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.e2eelab.skissm.proto.E2eeMessage.e2ee_message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_e2eelab_skissm_proto_e2ee_message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022e2ee_message.proto\022\030org.e2eelab.skissm" +
      ".proto\032\022e2ee_address.proto\032\027e2ee_message" +
      "_type.proto\"\355\001\n\014e2ee_message\022\017\n\007version\030" +
      "\001 \001(\r\0224\n\004from\030\002 \001(\0132&.org.e2eelab.skissm" +
      ".proto.e2ee_address\0222\n\002to\030\003 \001(\0132&.org.e2" +
      "eelab.skissm.proto.e2ee_address\022\022\n\nsessi" +
      "on_id\030\004 \001(\014\022=\n\010msg_type\030\005 \001(\0162+.org.e2ee" +
      "lab.skissm.proto.e2ee_message_type\022\017\n\007pa" +
      "yload\030\006 \001(\014B\'\n\030org.e2eelab.skissm.protoB" +
      "\013E2eeMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.e2eelab.skissm.proto.E2eeAddress.getDescriptor(),
          org.e2eelab.skissm.proto.E2eeMessageType.getDescriptor(),
        });
    internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_e2eelab_skissm_proto_e2ee_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_e2eelab_skissm_proto_e2ee_message_descriptor,
        new java.lang.String[] { "Version", "From", "To", "SessionId", "MsgType", "Payload", });
    org.e2eelab.skissm.proto.E2eeAddress.getDescriptor();
    org.e2eelab.skissm.proto.E2eeMessageType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
