// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skipped_message_key_node.proto

package org.e2eelab.skissm.proto;

public final class SkippedMessageKeyNode {
  private SkippedMessageKeyNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface skipped_message_key_nodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.e2eelab.skissm.proto.skipped_message_key_node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes ratchet_key_public = 1;</code>
     * @return The ratchetKeyPublic.
     */
    com.google.protobuf.ByteString getRatchetKeyPublic();

    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     * @return Whether the messageKey field is set.
     */
    boolean hasMessageKey();
    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     * @return The messageKey.
     */
    org.e2eelab.skissm.proto.MessageKey.message_key getMessageKey();
    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     */
    org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder getMessageKeyOrBuilder();
  }
  /**
   * Protobuf type {@code org.e2eelab.skissm.proto.skipped_message_key_node}
   */
  public static final class skipped_message_key_node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.e2eelab.skissm.proto.skipped_message_key_node)
      skipped_message_key_nodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use skipped_message_key_node.newBuilder() to construct.
    private skipped_message_key_node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private skipped_message_key_node() {
      ratchetKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new skipped_message_key_node();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private skipped_message_key_node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              ratchetKeyPublic_ = input.readBytes();
              break;
            }
            case 18: {
              org.e2eelab.skissm.proto.MessageKey.message_key.Builder subBuilder = null;
              if (messageKey_ != null) {
                subBuilder = messageKey_.toBuilder();
              }
              messageKey_ = input.readMessage(org.e2eelab.skissm.proto.MessageKey.message_key.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageKey_);
                messageKey_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.e2eelab.skissm.proto.SkippedMessageKeyNode.internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.e2eelab.skissm.proto.SkippedMessageKeyNode.internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.class, org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.Builder.class);
    }

    public static final int RATCHET_KEY_PUBLIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ratchetKeyPublic_;
    /**
     * <code>bytes ratchet_key_public = 1;</code>
     * @return The ratchetKeyPublic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRatchetKeyPublic() {
      return ratchetKeyPublic_;
    }

    public static final int MESSAGE_KEY_FIELD_NUMBER = 2;
    private org.e2eelab.skissm.proto.MessageKey.message_key messageKey_;
    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     * @return Whether the messageKey field is set.
     */
    @java.lang.Override
    public boolean hasMessageKey() {
      return messageKey_ != null;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     * @return The messageKey.
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.MessageKey.message_key getMessageKey() {
      return messageKey_ == null ? org.e2eelab.skissm.proto.MessageKey.message_key.getDefaultInstance() : messageKey_;
    }
    /**
     * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
     */
    @java.lang.Override
    public org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder getMessageKeyOrBuilder() {
      return getMessageKey();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ratchetKeyPublic_.isEmpty()) {
        output.writeBytes(1, ratchetKeyPublic_);
      }
      if (messageKey_ != null) {
        output.writeMessage(2, getMessageKey());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ratchetKeyPublic_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ratchetKeyPublic_);
      }
      if (messageKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMessageKey());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node)) {
        return super.equals(obj);
      }
      org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node other = (org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node) obj;

      if (!getRatchetKeyPublic()
          .equals(other.getRatchetKeyPublic())) return false;
      if (hasMessageKey() != other.hasMessageKey()) return false;
      if (hasMessageKey()) {
        if (!getMessageKey()
            .equals(other.getMessageKey())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RATCHET_KEY_PUBLIC_FIELD_NUMBER;
      hash = (53 * hash) + getRatchetKeyPublic().hashCode();
      if (hasMessageKey()) {
        hash = (37 * hash) + MESSAGE_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getMessageKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.e2eelab.skissm.proto.skipped_message_key_node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.e2eelab.skissm.proto.skipped_message_key_node)
        org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_nodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.e2eelab.skissm.proto.SkippedMessageKeyNode.internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.e2eelab.skissm.proto.SkippedMessageKeyNode.internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.class, org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.Builder.class);
      }

      // Construct using org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ratchetKeyPublic_ = com.google.protobuf.ByteString.EMPTY;

        if (messageKeyBuilder_ == null) {
          messageKey_ = null;
        } else {
          messageKey_ = null;
          messageKeyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.e2eelab.skissm.proto.SkippedMessageKeyNode.internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node getDefaultInstanceForType() {
        return org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.getDefaultInstance();
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node build() {
        org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node buildPartial() {
        org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node result = new org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node(this);
        result.ratchetKeyPublic_ = ratchetKeyPublic_;
        if (messageKeyBuilder_ == null) {
          result.messageKey_ = messageKey_;
        } else {
          result.messageKey_ = messageKeyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node) {
          return mergeFrom((org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node other) {
        if (other == org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node.getDefaultInstance()) return this;
        if (other.getRatchetKeyPublic() != com.google.protobuf.ByteString.EMPTY) {
          setRatchetKeyPublic(other.getRatchetKeyPublic());
        }
        if (other.hasMessageKey()) {
          mergeMessageKey(other.getMessageKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString ratchetKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ratchet_key_public = 1;</code>
       * @return The ratchetKeyPublic.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRatchetKeyPublic() {
        return ratchetKeyPublic_;
      }
      /**
       * <code>bytes ratchet_key_public = 1;</code>
       * @param value The ratchetKeyPublic to set.
       * @return This builder for chaining.
       */
      public Builder setRatchetKeyPublic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ratchetKeyPublic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ratchet_key_public = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRatchetKeyPublic() {
        
        ratchetKeyPublic_ = getDefaultInstance().getRatchetKeyPublic();
        onChanged();
        return this;
      }

      private org.e2eelab.skissm.proto.MessageKey.message_key messageKey_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.MessageKey.message_key, org.e2eelab.skissm.proto.MessageKey.message_key.Builder, org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder> messageKeyBuilder_;
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       * @return Whether the messageKey field is set.
       */
      public boolean hasMessageKey() {
        return messageKeyBuilder_ != null || messageKey_ != null;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       * @return The messageKey.
       */
      public org.e2eelab.skissm.proto.MessageKey.message_key getMessageKey() {
        if (messageKeyBuilder_ == null) {
          return messageKey_ == null ? org.e2eelab.skissm.proto.MessageKey.message_key.getDefaultInstance() : messageKey_;
        } else {
          return messageKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public Builder setMessageKey(org.e2eelab.skissm.proto.MessageKey.message_key value) {
        if (messageKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageKey_ = value;
          onChanged();
        } else {
          messageKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public Builder setMessageKey(
          org.e2eelab.skissm.proto.MessageKey.message_key.Builder builderForValue) {
        if (messageKeyBuilder_ == null) {
          messageKey_ = builderForValue.build();
          onChanged();
        } else {
          messageKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public Builder mergeMessageKey(org.e2eelab.skissm.proto.MessageKey.message_key value) {
        if (messageKeyBuilder_ == null) {
          if (messageKey_ != null) {
            messageKey_ =
              org.e2eelab.skissm.proto.MessageKey.message_key.newBuilder(messageKey_).mergeFrom(value).buildPartial();
          } else {
            messageKey_ = value;
          }
          onChanged();
        } else {
          messageKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public Builder clearMessageKey() {
        if (messageKeyBuilder_ == null) {
          messageKey_ = null;
          onChanged();
        } else {
          messageKey_ = null;
          messageKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public org.e2eelab.skissm.proto.MessageKey.message_key.Builder getMessageKeyBuilder() {
        
        onChanged();
        return getMessageKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      public org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder getMessageKeyOrBuilder() {
        if (messageKeyBuilder_ != null) {
          return messageKeyBuilder_.getMessageOrBuilder();
        } else {
          return messageKey_ == null ?
              org.e2eelab.skissm.proto.MessageKey.message_key.getDefaultInstance() : messageKey_;
        }
      }
      /**
       * <code>.org.e2eelab.skissm.proto.message_key message_key = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.e2eelab.skissm.proto.MessageKey.message_key, org.e2eelab.skissm.proto.MessageKey.message_key.Builder, org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder> 
          getMessageKeyFieldBuilder() {
        if (messageKeyBuilder_ == null) {
          messageKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.e2eelab.skissm.proto.MessageKey.message_key, org.e2eelab.skissm.proto.MessageKey.message_key.Builder, org.e2eelab.skissm.proto.MessageKey.message_keyOrBuilder>(
                  getMessageKey(),
                  getParentForChildren(),
                  isClean());
          messageKey_ = null;
        }
        return messageKeyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.e2eelab.skissm.proto.skipped_message_key_node)
    }

    // @@protoc_insertion_point(class_scope:org.e2eelab.skissm.proto.skipped_message_key_node)
    private static final org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node();
    }

    public static org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<skipped_message_key_node>
        PARSER = new com.google.protobuf.AbstractParser<skipped_message_key_node>() {
      @java.lang.Override
      public skipped_message_key_node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new skipped_message_key_node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<skipped_message_key_node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<skipped_message_key_node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.e2eelab.skissm.proto.SkippedMessageKeyNode.skipped_message_key_node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036skipped_message_key_node.proto\022\030org.e2" +
      "eelab.skissm.proto\032\021message_key.proto\"r\n" +
      "\030skipped_message_key_node\022\032\n\022ratchet_key" +
      "_public\030\001 \001(\014\022:\n\013message_key\030\002 \001(\0132%.org" +
      ".e2eelab.skissm.proto.message_keyB1\n\030org" +
      ".e2eelab.skissm.protoB\025SkippedMessageKey" +
      "Nodeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.e2eelab.skissm.proto.MessageKey.getDescriptor(),
        });
    internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_e2eelab_skissm_proto_skipped_message_key_node_descriptor,
        new java.lang.String[] { "RatchetKeyPublic", "MessageKey", });
    org.e2eelab.skissm.proto.MessageKey.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
