// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skissm/PendingGroupPreKey.proto

#include "skissm/PendingGroupPreKey.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace skissm {
constexpr PendingGroupPreKey::PendingGroupPreKey(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : outbound_group_session_id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , group_pre_key_plaintext_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , member_address_(nullptr){}
struct PendingGroupPreKeyDefaultTypeInternal {
  constexpr PendingGroupPreKeyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~PendingGroupPreKeyDefaultTypeInternal() {}
  union {
    PendingGroupPreKey _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PendingGroupPreKeyDefaultTypeInternal _PendingGroupPreKey_default_instance_;
}  // namespace skissm
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_skissm_2fPendingGroupPreKey_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_skissm_2fPendingGroupPreKey_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_skissm_2fPendingGroupPreKey_2eproto = nullptr;

const uint32_t TableStruct_skissm_2fPendingGroupPreKey_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::skissm::PendingGroupPreKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::skissm::PendingGroupPreKey, outbound_group_session_id_),
  PROTOBUF_FIELD_OFFSET(::skissm::PendingGroupPreKey, member_address_),
  PROTOBUF_FIELD_OFFSET(::skissm::PendingGroupPreKey, group_pre_key_plaintext_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::skissm::PendingGroupPreKey)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::skissm::_PendingGroupPreKey_default_instance_),
};

const char descriptor_table_protodef_skissm_2fPendingGroupPreKey_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037skissm/PendingGroupPreKey.proto\022\006skiss"
  "m\032\030skissm/E2eeAddress.proto\"\205\001\n\022PendingG"
  "roupPreKey\022!\n\031outbound_group_session_id\030"
  "\001 \001(\t\022+\n\016member_address\030\002 \001(\0132\023.skissm.E"
  "2eeAddress\022\037\n\027group_pre_key_plaintext\030\003 "
  "\001(\014B3\n\030org.e2eelab.skissm.protoB\027Pending"
  "GroupPreKeyProtob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_skissm_2fPendingGroupPreKey_2eproto_deps[1] = {
  &::descriptor_table_skissm_2fE2eeAddress_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_skissm_2fPendingGroupPreKey_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_skissm_2fPendingGroupPreKey_2eproto = {
  false, false, 264, descriptor_table_protodef_skissm_2fPendingGroupPreKey_2eproto, "skissm/PendingGroupPreKey.proto", 
  &descriptor_table_skissm_2fPendingGroupPreKey_2eproto_once, descriptor_table_skissm_2fPendingGroupPreKey_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_skissm_2fPendingGroupPreKey_2eproto::offsets,
  file_level_metadata_skissm_2fPendingGroupPreKey_2eproto, file_level_enum_descriptors_skissm_2fPendingGroupPreKey_2eproto, file_level_service_descriptors_skissm_2fPendingGroupPreKey_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_skissm_2fPendingGroupPreKey_2eproto_getter() {
  return &descriptor_table_skissm_2fPendingGroupPreKey_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_skissm_2fPendingGroupPreKey_2eproto(&descriptor_table_skissm_2fPendingGroupPreKey_2eproto);
namespace skissm {

// ===================================================================

class PendingGroupPreKey::_Internal {
 public:
  static const ::skissm::E2eeAddress& member_address(const PendingGroupPreKey* msg);
};

const ::skissm::E2eeAddress&
PendingGroupPreKey::_Internal::member_address(const PendingGroupPreKey* msg) {
  return *msg->member_address_;
}
void PendingGroupPreKey::clear_member_address() {
  if (GetArenaForAllocation() == nullptr && member_address_ != nullptr) {
    delete member_address_;
  }
  member_address_ = nullptr;
}
PendingGroupPreKey::PendingGroupPreKey(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:skissm.PendingGroupPreKey)
}
PendingGroupPreKey::PendingGroupPreKey(const PendingGroupPreKey& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  outbound_group_session_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    outbound_group_session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_outbound_group_session_id().empty()) {
    outbound_group_session_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_outbound_group_session_id(), 
      GetArenaForAllocation());
  }
  group_pre_key_plaintext_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    group_pre_key_plaintext_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_group_pre_key_plaintext().empty()) {
    group_pre_key_plaintext_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_group_pre_key_plaintext(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_member_address()) {
    member_address_ = new ::skissm::E2eeAddress(*from.member_address_);
  } else {
    member_address_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:skissm.PendingGroupPreKey)
}

inline void PendingGroupPreKey::SharedCtor() {
outbound_group_session_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  outbound_group_session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
group_pre_key_plaintext_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  group_pre_key_plaintext_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
member_address_ = nullptr;
}

PendingGroupPreKey::~PendingGroupPreKey() {
  // @@protoc_insertion_point(destructor:skissm.PendingGroupPreKey)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void PendingGroupPreKey::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  outbound_group_session_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  group_pre_key_plaintext_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete member_address_;
}

void PendingGroupPreKey::ArenaDtor(void* object) {
  PendingGroupPreKey* _this = reinterpret_cast< PendingGroupPreKey* >(object);
  (void)_this;
}
void PendingGroupPreKey::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PendingGroupPreKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PendingGroupPreKey::Clear() {
// @@protoc_insertion_point(message_clear_start:skissm.PendingGroupPreKey)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  outbound_group_session_id_.ClearToEmpty();
  group_pre_key_plaintext_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && member_address_ != nullptr) {
    delete member_address_;
  }
  member_address_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PendingGroupPreKey::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string outbound_group_session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_outbound_group_session_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "skissm.PendingGroupPreKey.outbound_group_session_id"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .skissm.E2eeAddress member_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_member_address(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes group_pre_key_plaintext = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_group_pre_key_plaintext();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PendingGroupPreKey::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:skissm.PendingGroupPreKey)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string outbound_group_session_id = 1;
  if (!this->_internal_outbound_group_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_outbound_group_session_id().data(), static_cast<int>(this->_internal_outbound_group_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "skissm.PendingGroupPreKey.outbound_group_session_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_outbound_group_session_id(), target);
  }

  // .skissm.E2eeAddress member_address = 2;
  if (this->_internal_has_member_address()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::member_address(this), target, stream);
  }

  // bytes group_pre_key_plaintext = 3;
  if (!this->_internal_group_pre_key_plaintext().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_group_pre_key_plaintext(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:skissm.PendingGroupPreKey)
  return target;
}

size_t PendingGroupPreKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:skissm.PendingGroupPreKey)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string outbound_group_session_id = 1;
  if (!this->_internal_outbound_group_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_outbound_group_session_id());
  }

  // bytes group_pre_key_plaintext = 3;
  if (!this->_internal_group_pre_key_plaintext().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_group_pre_key_plaintext());
  }

  // .skissm.E2eeAddress member_address = 2;
  if (this->_internal_has_member_address()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *member_address_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PendingGroupPreKey::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PendingGroupPreKey::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PendingGroupPreKey::GetClassData() const { return &_class_data_; }

void PendingGroupPreKey::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PendingGroupPreKey *>(to)->MergeFrom(
      static_cast<const PendingGroupPreKey &>(from));
}


void PendingGroupPreKey::MergeFrom(const PendingGroupPreKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:skissm.PendingGroupPreKey)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_outbound_group_session_id().empty()) {
    _internal_set_outbound_group_session_id(from._internal_outbound_group_session_id());
  }
  if (!from._internal_group_pre_key_plaintext().empty()) {
    _internal_set_group_pre_key_plaintext(from._internal_group_pre_key_plaintext());
  }
  if (from._internal_has_member_address()) {
    _internal_mutable_member_address()->::skissm::E2eeAddress::MergeFrom(from._internal_member_address());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PendingGroupPreKey::CopyFrom(const PendingGroupPreKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skissm.PendingGroupPreKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PendingGroupPreKey::IsInitialized() const {
  return true;
}

void PendingGroupPreKey::InternalSwap(PendingGroupPreKey* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &outbound_group_session_id_, lhs_arena,
      &other->outbound_group_session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &group_pre_key_plaintext_, lhs_arena,
      &other->group_pre_key_plaintext_, rhs_arena
  );
  swap(member_address_, other->member_address_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PendingGroupPreKey::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_skissm_2fPendingGroupPreKey_2eproto_getter, &descriptor_table_skissm_2fPendingGroupPreKey_2eproto_once,
      file_level_metadata_skissm_2fPendingGroupPreKey_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace skissm
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::skissm::PendingGroupPreKey* Arena::CreateMaybeMessage< ::skissm::PendingGroupPreKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::skissm::PendingGroupPreKey >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
