// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skissm/RegisterUserRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_skissm_2fRegisterUserRequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_skissm_2fRegisterUserRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "skissm/IdentityKeyPublic.pb.h"
#include "skissm/SignedPreKeyPublic.pb.h"
#include "skissm/OneTimePreKeyPublic.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_skissm_2fRegisterUserRequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_skissm_2fRegisterUserRequest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_skissm_2fRegisterUserRequest_2eproto;
namespace skissm {
class RegisterUserRequest;
struct RegisterUserRequestDefaultTypeInternal;
extern RegisterUserRequestDefaultTypeInternal _RegisterUserRequest_default_instance_;
}  // namespace skissm
PROTOBUF_NAMESPACE_OPEN
template<> ::skissm::RegisterUserRequest* Arena::CreateMaybeMessage<::skissm::RegisterUserRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace skissm {

// ===================================================================

class RegisterUserRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:skissm.RegisterUserRequest) */ {
 public:
  inline RegisterUserRequest() : RegisterUserRequest(nullptr) {}
  ~RegisterUserRequest() override;
  explicit constexpr RegisterUserRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RegisterUserRequest(const RegisterUserRequest& from);
  RegisterUserRequest(RegisterUserRequest&& from) noexcept
    : RegisterUserRequest() {
    *this = ::std::move(from);
  }

  inline RegisterUserRequest& operator=(const RegisterUserRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterUserRequest& operator=(RegisterUserRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegisterUserRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegisterUserRequest* internal_default_instance() {
    return reinterpret_cast<const RegisterUserRequest*>(
               &_RegisterUserRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegisterUserRequest& a, RegisterUserRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterUserRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterUserRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegisterUserRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RegisterUserRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RegisterUserRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RegisterUserRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterUserRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "skissm.RegisterUserRequest";
  }
  protected:
  explicit RegisterUserRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOneTimePreKeysFieldNumber = 8,
    kUserNameFieldNumber = 1,
    kDeviceIdFieldNumber = 2,
    kAuthenticatorFieldNumber = 3,
    kAuthCodeFieldNumber = 4,
    kE2EePackIdFieldNumber = 5,
    kIdentityKeyPublicFieldNumber = 6,
    kSignedPreKeyPublicFieldNumber = 7,
  };
  // repeated .skissm.OneTimePreKeyPublic one_time_pre_keys = 8;
  int one_time_pre_keys_size() const;
  private:
  int _internal_one_time_pre_keys_size() const;
  public:
  void clear_one_time_pre_keys();
  ::skissm::OneTimePreKeyPublic* mutable_one_time_pre_keys(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::skissm::OneTimePreKeyPublic >*
      mutable_one_time_pre_keys();
  private:
  const ::skissm::OneTimePreKeyPublic& _internal_one_time_pre_keys(int index) const;
  ::skissm::OneTimePreKeyPublic* _internal_add_one_time_pre_keys();
  public:
  const ::skissm::OneTimePreKeyPublic& one_time_pre_keys(int index) const;
  ::skissm::OneTimePreKeyPublic* add_one_time_pre_keys();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::skissm::OneTimePreKeyPublic >&
      one_time_pre_keys() const;

  // string user_name = 1;
  void clear_user_name();
  const std::string& user_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_name();
  PROTOBUF_NODISCARD std::string* release_user_name();
  void set_allocated_user_name(std::string* user_name);
  private:
  const std::string& _internal_user_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_name(const std::string& value);
  std::string* _internal_mutable_user_name();
  public:

  // string device_id = 2;
  void clear_device_id();
  const std::string& device_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_id();
  PROTOBUF_NODISCARD std::string* release_device_id();
  void set_allocated_device_id(std::string* device_id);
  private:
  const std::string& _internal_device_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const std::string& value);
  std::string* _internal_mutable_device_id();
  public:

  // string authenticator = 3;
  void clear_authenticator();
  const std::string& authenticator() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_authenticator(ArgT0&& arg0, ArgT... args);
  std::string* mutable_authenticator();
  PROTOBUF_NODISCARD std::string* release_authenticator();
  void set_allocated_authenticator(std::string* authenticator);
  private:
  const std::string& _internal_authenticator() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_authenticator(const std::string& value);
  std::string* _internal_mutable_authenticator();
  public:

  // string auth_code = 4;
  void clear_auth_code();
  const std::string& auth_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_auth_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_auth_code();
  PROTOBUF_NODISCARD std::string* release_auth_code();
  void set_allocated_auth_code(std::string* auth_code);
  private:
  const std::string& _internal_auth_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_auth_code(const std::string& value);
  std::string* _internal_mutable_auth_code();
  public:

  // string e2ee_pack_id = 5;
  void clear_e2ee_pack_id();
  const std::string& e2ee_pack_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_e2ee_pack_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_e2ee_pack_id();
  PROTOBUF_NODISCARD std::string* release_e2ee_pack_id();
  void set_allocated_e2ee_pack_id(std::string* e2ee_pack_id);
  private:
  const std::string& _internal_e2ee_pack_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_e2ee_pack_id(const std::string& value);
  std::string* _internal_mutable_e2ee_pack_id();
  public:

  // .skissm.IdentityKeyPublic identity_key_public = 6;
  bool has_identity_key_public() const;
  private:
  bool _internal_has_identity_key_public() const;
  public:
  void clear_identity_key_public();
  const ::skissm::IdentityKeyPublic& identity_key_public() const;
  PROTOBUF_NODISCARD ::skissm::IdentityKeyPublic* release_identity_key_public();
  ::skissm::IdentityKeyPublic* mutable_identity_key_public();
  void set_allocated_identity_key_public(::skissm::IdentityKeyPublic* identity_key_public);
  private:
  const ::skissm::IdentityKeyPublic& _internal_identity_key_public() const;
  ::skissm::IdentityKeyPublic* _internal_mutable_identity_key_public();
  public:
  void unsafe_arena_set_allocated_identity_key_public(
      ::skissm::IdentityKeyPublic* identity_key_public);
  ::skissm::IdentityKeyPublic* unsafe_arena_release_identity_key_public();

  // .skissm.SignedPreKeyPublic signed_pre_key_public = 7;
  bool has_signed_pre_key_public() const;
  private:
  bool _internal_has_signed_pre_key_public() const;
  public:
  void clear_signed_pre_key_public();
  const ::skissm::SignedPreKeyPublic& signed_pre_key_public() const;
  PROTOBUF_NODISCARD ::skissm::SignedPreKeyPublic* release_signed_pre_key_public();
  ::skissm::SignedPreKeyPublic* mutable_signed_pre_key_public();
  void set_allocated_signed_pre_key_public(::skissm::SignedPreKeyPublic* signed_pre_key_public);
  private:
  const ::skissm::SignedPreKeyPublic& _internal_signed_pre_key_public() const;
  ::skissm::SignedPreKeyPublic* _internal_mutable_signed_pre_key_public();
  public:
  void unsafe_arena_set_allocated_signed_pre_key_public(
      ::skissm::SignedPreKeyPublic* signed_pre_key_public);
  ::skissm::SignedPreKeyPublic* unsafe_arena_release_signed_pre_key_public();

  // @@protoc_insertion_point(class_scope:skissm.RegisterUserRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::skissm::OneTimePreKeyPublic > one_time_pre_keys_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr authenticator_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr auth_code_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr e2ee_pack_id_;
  ::skissm::IdentityKeyPublic* identity_key_public_;
  ::skissm::SignedPreKeyPublic* signed_pre_key_public_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_skissm_2fRegisterUserRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterUserRequest

// string user_name = 1;
inline void RegisterUserRequest::clear_user_name() {
  user_name_.ClearToEmpty();
}
inline const std::string& RegisterUserRequest::user_name() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.user_name)
  return _internal_user_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterUserRequest::set_user_name(ArgT0&& arg0, ArgT... args) {
 
 user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:skissm.RegisterUserRequest.user_name)
}
inline std::string* RegisterUserRequest::mutable_user_name() {
  std::string* _s = _internal_mutable_user_name();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.user_name)
  return _s;
}
inline const std::string& RegisterUserRequest::_internal_user_name() const {
  return user_name_.Get();
}
inline void RegisterUserRequest::_internal_set_user_name(const std::string& value) {
  
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::_internal_mutable_user_name() {
  
  return user_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::release_user_name() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.user_name)
  return user_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RegisterUserRequest::set_allocated_user_name(std::string* user_name) {
  if (user_name != nullptr) {
    
  } else {
    
  }
  user_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (user_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    user_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.user_name)
}

// string device_id = 2;
inline void RegisterUserRequest::clear_device_id() {
  device_id_.ClearToEmpty();
}
inline const std::string& RegisterUserRequest::device_id() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.device_id)
  return _internal_device_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterUserRequest::set_device_id(ArgT0&& arg0, ArgT... args) {
 
 device_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:skissm.RegisterUserRequest.device_id)
}
inline std::string* RegisterUserRequest::mutable_device_id() {
  std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.device_id)
  return _s;
}
inline const std::string& RegisterUserRequest::_internal_device_id() const {
  return device_id_.Get();
}
inline void RegisterUserRequest::_internal_set_device_id(const std::string& value) {
  
  device_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::_internal_mutable_device_id() {
  
  return device_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::release_device_id() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.device_id)
  return device_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RegisterUserRequest::set_allocated_device_id(std::string* device_id) {
  if (device_id != nullptr) {
    
  } else {
    
  }
  device_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (device_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    device_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.device_id)
}

// string authenticator = 3;
inline void RegisterUserRequest::clear_authenticator() {
  authenticator_.ClearToEmpty();
}
inline const std::string& RegisterUserRequest::authenticator() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.authenticator)
  return _internal_authenticator();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterUserRequest::set_authenticator(ArgT0&& arg0, ArgT... args) {
 
 authenticator_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:skissm.RegisterUserRequest.authenticator)
}
inline std::string* RegisterUserRequest::mutable_authenticator() {
  std::string* _s = _internal_mutable_authenticator();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.authenticator)
  return _s;
}
inline const std::string& RegisterUserRequest::_internal_authenticator() const {
  return authenticator_.Get();
}
inline void RegisterUserRequest::_internal_set_authenticator(const std::string& value) {
  
  authenticator_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::_internal_mutable_authenticator() {
  
  return authenticator_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::release_authenticator() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.authenticator)
  return authenticator_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RegisterUserRequest::set_allocated_authenticator(std::string* authenticator) {
  if (authenticator != nullptr) {
    
  } else {
    
  }
  authenticator_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), authenticator,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (authenticator_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    authenticator_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.authenticator)
}

// string auth_code = 4;
inline void RegisterUserRequest::clear_auth_code() {
  auth_code_.ClearToEmpty();
}
inline const std::string& RegisterUserRequest::auth_code() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.auth_code)
  return _internal_auth_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterUserRequest::set_auth_code(ArgT0&& arg0, ArgT... args) {
 
 auth_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:skissm.RegisterUserRequest.auth_code)
}
inline std::string* RegisterUserRequest::mutable_auth_code() {
  std::string* _s = _internal_mutable_auth_code();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.auth_code)
  return _s;
}
inline const std::string& RegisterUserRequest::_internal_auth_code() const {
  return auth_code_.Get();
}
inline void RegisterUserRequest::_internal_set_auth_code(const std::string& value) {
  
  auth_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::_internal_mutable_auth_code() {
  
  return auth_code_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::release_auth_code() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.auth_code)
  return auth_code_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RegisterUserRequest::set_allocated_auth_code(std::string* auth_code) {
  if (auth_code != nullptr) {
    
  } else {
    
  }
  auth_code_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), auth_code,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (auth_code_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    auth_code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.auth_code)
}

// string e2ee_pack_id = 5;
inline void RegisterUserRequest::clear_e2ee_pack_id() {
  e2ee_pack_id_.ClearToEmpty();
}
inline const std::string& RegisterUserRequest::e2ee_pack_id() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.e2ee_pack_id)
  return _internal_e2ee_pack_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterUserRequest::set_e2ee_pack_id(ArgT0&& arg0, ArgT... args) {
 
 e2ee_pack_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:skissm.RegisterUserRequest.e2ee_pack_id)
}
inline std::string* RegisterUserRequest::mutable_e2ee_pack_id() {
  std::string* _s = _internal_mutable_e2ee_pack_id();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.e2ee_pack_id)
  return _s;
}
inline const std::string& RegisterUserRequest::_internal_e2ee_pack_id() const {
  return e2ee_pack_id_.Get();
}
inline void RegisterUserRequest::_internal_set_e2ee_pack_id(const std::string& value) {
  
  e2ee_pack_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::_internal_mutable_e2ee_pack_id() {
  
  return e2ee_pack_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* RegisterUserRequest::release_e2ee_pack_id() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.e2ee_pack_id)
  return e2ee_pack_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void RegisterUserRequest::set_allocated_e2ee_pack_id(std::string* e2ee_pack_id) {
  if (e2ee_pack_id != nullptr) {
    
  } else {
    
  }
  e2ee_pack_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), e2ee_pack_id,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (e2ee_pack_id_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    e2ee_pack_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.e2ee_pack_id)
}

// .skissm.IdentityKeyPublic identity_key_public = 6;
inline bool RegisterUserRequest::_internal_has_identity_key_public() const {
  return this != internal_default_instance() && identity_key_public_ != nullptr;
}
inline bool RegisterUserRequest::has_identity_key_public() const {
  return _internal_has_identity_key_public();
}
inline const ::skissm::IdentityKeyPublic& RegisterUserRequest::_internal_identity_key_public() const {
  const ::skissm::IdentityKeyPublic* p = identity_key_public_;
  return p != nullptr ? *p : reinterpret_cast<const ::skissm::IdentityKeyPublic&>(
      ::skissm::_IdentityKeyPublic_default_instance_);
}
inline const ::skissm::IdentityKeyPublic& RegisterUserRequest::identity_key_public() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.identity_key_public)
  return _internal_identity_key_public();
}
inline void RegisterUserRequest::unsafe_arena_set_allocated_identity_key_public(
    ::skissm::IdentityKeyPublic* identity_key_public) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(identity_key_public_);
  }
  identity_key_public_ = identity_key_public;
  if (identity_key_public) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skissm.RegisterUserRequest.identity_key_public)
}
inline ::skissm::IdentityKeyPublic* RegisterUserRequest::release_identity_key_public() {
  
  ::skissm::IdentityKeyPublic* temp = identity_key_public_;
  identity_key_public_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::skissm::IdentityKeyPublic* RegisterUserRequest::unsafe_arena_release_identity_key_public() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.identity_key_public)
  
  ::skissm::IdentityKeyPublic* temp = identity_key_public_;
  identity_key_public_ = nullptr;
  return temp;
}
inline ::skissm::IdentityKeyPublic* RegisterUserRequest::_internal_mutable_identity_key_public() {
  
  if (identity_key_public_ == nullptr) {
    auto* p = CreateMaybeMessage<::skissm::IdentityKeyPublic>(GetArenaForAllocation());
    identity_key_public_ = p;
  }
  return identity_key_public_;
}
inline ::skissm::IdentityKeyPublic* RegisterUserRequest::mutable_identity_key_public() {
  ::skissm::IdentityKeyPublic* _msg = _internal_mutable_identity_key_public();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.identity_key_public)
  return _msg;
}
inline void RegisterUserRequest::set_allocated_identity_key_public(::skissm::IdentityKeyPublic* identity_key_public) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(identity_key_public_);
  }
  if (identity_key_public) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(identity_key_public));
    if (message_arena != submessage_arena) {
      identity_key_public = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, identity_key_public, submessage_arena);
    }
    
  } else {
    
  }
  identity_key_public_ = identity_key_public;
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.identity_key_public)
}

// .skissm.SignedPreKeyPublic signed_pre_key_public = 7;
inline bool RegisterUserRequest::_internal_has_signed_pre_key_public() const {
  return this != internal_default_instance() && signed_pre_key_public_ != nullptr;
}
inline bool RegisterUserRequest::has_signed_pre_key_public() const {
  return _internal_has_signed_pre_key_public();
}
inline const ::skissm::SignedPreKeyPublic& RegisterUserRequest::_internal_signed_pre_key_public() const {
  const ::skissm::SignedPreKeyPublic* p = signed_pre_key_public_;
  return p != nullptr ? *p : reinterpret_cast<const ::skissm::SignedPreKeyPublic&>(
      ::skissm::_SignedPreKeyPublic_default_instance_);
}
inline const ::skissm::SignedPreKeyPublic& RegisterUserRequest::signed_pre_key_public() const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.signed_pre_key_public)
  return _internal_signed_pre_key_public();
}
inline void RegisterUserRequest::unsafe_arena_set_allocated_signed_pre_key_public(
    ::skissm::SignedPreKeyPublic* signed_pre_key_public) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(signed_pre_key_public_);
  }
  signed_pre_key_public_ = signed_pre_key_public;
  if (signed_pre_key_public) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:skissm.RegisterUserRequest.signed_pre_key_public)
}
inline ::skissm::SignedPreKeyPublic* RegisterUserRequest::release_signed_pre_key_public() {
  
  ::skissm::SignedPreKeyPublic* temp = signed_pre_key_public_;
  signed_pre_key_public_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::skissm::SignedPreKeyPublic* RegisterUserRequest::unsafe_arena_release_signed_pre_key_public() {
  // @@protoc_insertion_point(field_release:skissm.RegisterUserRequest.signed_pre_key_public)
  
  ::skissm::SignedPreKeyPublic* temp = signed_pre_key_public_;
  signed_pre_key_public_ = nullptr;
  return temp;
}
inline ::skissm::SignedPreKeyPublic* RegisterUserRequest::_internal_mutable_signed_pre_key_public() {
  
  if (signed_pre_key_public_ == nullptr) {
    auto* p = CreateMaybeMessage<::skissm::SignedPreKeyPublic>(GetArenaForAllocation());
    signed_pre_key_public_ = p;
  }
  return signed_pre_key_public_;
}
inline ::skissm::SignedPreKeyPublic* RegisterUserRequest::mutable_signed_pre_key_public() {
  ::skissm::SignedPreKeyPublic* _msg = _internal_mutable_signed_pre_key_public();
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.signed_pre_key_public)
  return _msg;
}
inline void RegisterUserRequest::set_allocated_signed_pre_key_public(::skissm::SignedPreKeyPublic* signed_pre_key_public) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(signed_pre_key_public_);
  }
  if (signed_pre_key_public) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(signed_pre_key_public));
    if (message_arena != submessage_arena) {
      signed_pre_key_public = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signed_pre_key_public, submessage_arena);
    }
    
  } else {
    
  }
  signed_pre_key_public_ = signed_pre_key_public;
  // @@protoc_insertion_point(field_set_allocated:skissm.RegisterUserRequest.signed_pre_key_public)
}

// repeated .skissm.OneTimePreKeyPublic one_time_pre_keys = 8;
inline int RegisterUserRequest::_internal_one_time_pre_keys_size() const {
  return one_time_pre_keys_.size();
}
inline int RegisterUserRequest::one_time_pre_keys_size() const {
  return _internal_one_time_pre_keys_size();
}
inline ::skissm::OneTimePreKeyPublic* RegisterUserRequest::mutable_one_time_pre_keys(int index) {
  // @@protoc_insertion_point(field_mutable:skissm.RegisterUserRequest.one_time_pre_keys)
  return one_time_pre_keys_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::skissm::OneTimePreKeyPublic >*
RegisterUserRequest::mutable_one_time_pre_keys() {
  // @@protoc_insertion_point(field_mutable_list:skissm.RegisterUserRequest.one_time_pre_keys)
  return &one_time_pre_keys_;
}
inline const ::skissm::OneTimePreKeyPublic& RegisterUserRequest::_internal_one_time_pre_keys(int index) const {
  return one_time_pre_keys_.Get(index);
}
inline const ::skissm::OneTimePreKeyPublic& RegisterUserRequest::one_time_pre_keys(int index) const {
  // @@protoc_insertion_point(field_get:skissm.RegisterUserRequest.one_time_pre_keys)
  return _internal_one_time_pre_keys(index);
}
inline ::skissm::OneTimePreKeyPublic* RegisterUserRequest::_internal_add_one_time_pre_keys() {
  return one_time_pre_keys_.Add();
}
inline ::skissm::OneTimePreKeyPublic* RegisterUserRequest::add_one_time_pre_keys() {
  ::skissm::OneTimePreKeyPublic* _add = _internal_add_one_time_pre_keys();
  // @@protoc_insertion_point(field_add:skissm.RegisterUserRequest.one_time_pre_keys)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::skissm::OneTimePreKeyPublic >&
RegisterUserRequest::one_time_pre_keys() const {
  // @@protoc_insertion_point(field_list:skissm.RegisterUserRequest.one_time_pre_keys)
  return one_time_pre_keys_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace skissm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_skissm_2fRegisterUserRequest_2eproto
