// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skissm/SignedPreKey.proto

#include "skissm/SignedPreKey.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace skissm {
constexpr SignedPreKey::SignedPreKey(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : signature_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , key_pair_(nullptr)
  , ttl_(int64_t{0})
  , spk_id_(0u){}
struct SignedPreKeyDefaultTypeInternal {
  constexpr SignedPreKeyDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SignedPreKeyDefaultTypeInternal() {}
  union {
    SignedPreKey _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SignedPreKeyDefaultTypeInternal _SignedPreKey_default_instance_;
}  // namespace skissm
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_skissm_2fSignedPreKey_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_skissm_2fSignedPreKey_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_skissm_2fSignedPreKey_2eproto = nullptr;

const uint32_t TableStruct_skissm_2fSignedPreKey_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::skissm::SignedPreKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::skissm::SignedPreKey, spk_id_),
  PROTOBUF_FIELD_OFFSET(::skissm::SignedPreKey, key_pair_),
  PROTOBUF_FIELD_OFFSET(::skissm::SignedPreKey, signature_),
  PROTOBUF_FIELD_OFFSET(::skissm::SignedPreKey, ttl_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::skissm::SignedPreKey)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::skissm::_SignedPreKey_default_instance_),
};

const char descriptor_table_protodef_skissm_2fSignedPreKey_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031skissm/SignedPreKey.proto\022\006skissm\032\024ski"
  "ssm/KeyPair.proto\"a\n\014SignedPreKey\022\016\n\006spk"
  "_id\030\001 \001(\r\022!\n\010key_pair\030\002 \001(\0132\017.skissm.Key"
  "Pair\022\021\n\tsignature\030\003 \001(\014\022\013\n\003ttl\030\004 \001(\003B-\n\030"
  "org.e2eelab.skissm.protoB\021SignedPreKeyPr"
  "otob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_skissm_2fSignedPreKey_2eproto_deps[1] = {
  &::descriptor_table_skissm_2fKeyPair_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_skissm_2fSignedPreKey_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_skissm_2fSignedPreKey_2eproto = {
  false, false, 211, descriptor_table_protodef_skissm_2fSignedPreKey_2eproto, "skissm/SignedPreKey.proto", 
  &descriptor_table_skissm_2fSignedPreKey_2eproto_once, descriptor_table_skissm_2fSignedPreKey_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_skissm_2fSignedPreKey_2eproto::offsets,
  file_level_metadata_skissm_2fSignedPreKey_2eproto, file_level_enum_descriptors_skissm_2fSignedPreKey_2eproto, file_level_service_descriptors_skissm_2fSignedPreKey_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_skissm_2fSignedPreKey_2eproto_getter() {
  return &descriptor_table_skissm_2fSignedPreKey_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_skissm_2fSignedPreKey_2eproto(&descriptor_table_skissm_2fSignedPreKey_2eproto);
namespace skissm {

// ===================================================================

class SignedPreKey::_Internal {
 public:
  static const ::skissm::KeyPair& key_pair(const SignedPreKey* msg);
};

const ::skissm::KeyPair&
SignedPreKey::_Internal::key_pair(const SignedPreKey* msg) {
  return *msg->key_pair_;
}
void SignedPreKey::clear_key_pair() {
  if (GetArenaForAllocation() == nullptr && key_pair_ != nullptr) {
    delete key_pair_;
  }
  key_pair_ = nullptr;
}
SignedPreKey::SignedPreKey(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:skissm.SignedPreKey)
}
SignedPreKey::SignedPreKey(const SignedPreKey& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  signature_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    signature_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_signature().empty()) {
    signature_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_signature(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_key_pair()) {
    key_pair_ = new ::skissm::KeyPair(*from.key_pair_);
  } else {
    key_pair_ = nullptr;
  }
  ::memcpy(&ttl_, &from.ttl_,
    static_cast<size_t>(reinterpret_cast<char*>(&spk_id_) -
    reinterpret_cast<char*>(&ttl_)) + sizeof(spk_id_));
  // @@protoc_insertion_point(copy_constructor:skissm.SignedPreKey)
}

inline void SignedPreKey::SharedCtor() {
signature_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  signature_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&key_pair_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&spk_id_) -
    reinterpret_cast<char*>(&key_pair_)) + sizeof(spk_id_));
}

SignedPreKey::~SignedPreKey() {
  // @@protoc_insertion_point(destructor:skissm.SignedPreKey)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SignedPreKey::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  signature_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete key_pair_;
}

void SignedPreKey::ArenaDtor(void* object) {
  SignedPreKey* _this = reinterpret_cast< SignedPreKey* >(object);
  (void)_this;
}
void SignedPreKey::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SignedPreKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SignedPreKey::Clear() {
// @@protoc_insertion_point(message_clear_start:skissm.SignedPreKey)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  signature_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && key_pair_ != nullptr) {
    delete key_pair_;
  }
  key_pair_ = nullptr;
  ::memset(&ttl_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&spk_id_) -
      reinterpret_cast<char*>(&ttl_)) + sizeof(spk_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SignedPreKey::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 spk_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          spk_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .skissm.KeyPair key_pair = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_key_pair(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes signature = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_signature();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 ttl = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          ttl_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SignedPreKey::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:skissm.SignedPreKey)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 spk_id = 1;
  if (this->_internal_spk_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_spk_id(), target);
  }

  // .skissm.KeyPair key_pair = 2;
  if (this->_internal_has_key_pair()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::key_pair(this), target, stream);
  }

  // bytes signature = 3;
  if (!this->_internal_signature().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_signature(), target);
  }

  // int64 ttl = 4;
  if (this->_internal_ttl() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_ttl(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:skissm.SignedPreKey)
  return target;
}

size_t SignedPreKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:skissm.SignedPreKey)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes signature = 3;
  if (!this->_internal_signature().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_signature());
  }

  // .skissm.KeyPair key_pair = 2;
  if (this->_internal_has_key_pair()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *key_pair_);
  }

  // int64 ttl = 4;
  if (this->_internal_ttl() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_ttl());
  }

  // uint32 spk_id = 1;
  if (this->_internal_spk_id() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_spk_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SignedPreKey::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SignedPreKey::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SignedPreKey::GetClassData() const { return &_class_data_; }

void SignedPreKey::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SignedPreKey *>(to)->MergeFrom(
      static_cast<const SignedPreKey &>(from));
}


void SignedPreKey::MergeFrom(const SignedPreKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:skissm.SignedPreKey)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_signature().empty()) {
    _internal_set_signature(from._internal_signature());
  }
  if (from._internal_has_key_pair()) {
    _internal_mutable_key_pair()->::skissm::KeyPair::MergeFrom(from._internal_key_pair());
  }
  if (from._internal_ttl() != 0) {
    _internal_set_ttl(from._internal_ttl());
  }
  if (from._internal_spk_id() != 0) {
    _internal_set_spk_id(from._internal_spk_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SignedPreKey::CopyFrom(const SignedPreKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skissm.SignedPreKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignedPreKey::IsInitialized() const {
  return true;
}

void SignedPreKey::InternalSwap(SignedPreKey* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &signature_, lhs_arena,
      &other->signature_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SignedPreKey, spk_id_)
      + sizeof(SignedPreKey::spk_id_)
      - PROTOBUF_FIELD_OFFSET(SignedPreKey, key_pair_)>(
          reinterpret_cast<char*>(&key_pair_),
          reinterpret_cast<char*>(&other->key_pair_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SignedPreKey::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_skissm_2fSignedPreKey_2eproto_getter, &descriptor_table_skissm_2fSignedPreKey_2eproto_once,
      file_level_metadata_skissm_2fSignedPreKey_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace skissm
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::skissm::SignedPreKey* Arena::CreateMaybeMessage< ::skissm::SignedPreKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::skissm::SignedPreKey >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
